"""
Strategy T09598: dual_rsi
Family: dual_rsi
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 12, 'ema_slow': 88, 'atr_period': 13, 'sl_atr': 1.8146, 'tp_atr': 2.9913, 'cooldown': 7, 'session_start': 7, 'session_end': 18, 'rsi_fast': 9, 'rsi_slow': 23}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["rsi_f"] = ta.momentum.rsi(df["Close"], window=p["rsi_fast"])
    df["rsi_s"] = ta.momentum.rsi(df["Close"], window=p["rsi_slow"])
    df["signal"] = 0
    long_cond = uptrend & (df["rsi_f"] > df["rsi_s"]) & (df["rsi_f"].shift(1) <= df["rsi_s"].shift(1)) & (df["rsi_s"] < 50)
    short_cond = downtrend & (df["rsi_f"] < df["rsi_s"]) & (df["rsi_f"].shift(1) >= df["rsi_s"].shift(1)) & (df["rsi_s"] > 50)
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
