"""
Strategy T00185: breakout_nbar
Family: breakout_nbar
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 15, 'ema_slow': 90, 'atr_period': 16, 'sl_atr': 1.0772, 'tp_atr': 3.2259, 'lookback': 16}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["hi_n"] = df["High"].rolling(window=p["lookback"]).max().shift(1)
    df["lo_n"] = df["Low"].rolling(window=p["lookback"]).min().shift(1)
    df["signal"] = 0
    long_cond = uptrend & (df["Close"] > df["hi_n"]) & (df["Close"].shift(1) <= df["hi_n"].shift(1))
    short_cond = downtrend & (df["Close"] < df["lo_n"]) & (df["Close"].shift(1) >= df["lo_n"].shift(1))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
