"""
Strategy T09690: hybrid_vol_rsi_bb
Family: hybrid_vol_rsi_bb
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 15, 'ema_slow': 33, 'atr_period': 19, 'sl_atr': 2.2646, 'tp_atr': 2.3422, 'cooldown': 7, 'session_start': 11, 'session_end': 18, 'rsi_period': 14, 'rsi_low': 26, 'rsi_high': 76, 'bb_period': 26, 'bb_std': 2.328, 'vol_mult': 2.0019}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])
    df["bb_l"] = ta.volatility.bollinger_lband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])
    df["bb_h"] = ta.volatility.bollinger_hband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])
    df["vol_ma"] = df["Volume"].rolling(window=20).mean()
    df["vol_spike"] = df["Volume"] > p["vol_mult"] * df["vol_ma"]
    df["signal"] = 0
    long_cond = uptrend & (((df["rsi"] < p["rsi_low"]) & (df["rsi"].shift(1) >= p["rsi_low"])) | ((df["Close"] <= df["bb_l"]) & (df["Close"].shift(1) > df["bb_l"].shift(1))) | (df["vol_spike"] & (df["Close"] > df["Open"]) & (df["Close"] > df["Close"].shift(1))))
    short_cond = downtrend & (((df["rsi"] > p["rsi_high"]) & (df["rsi"].shift(1) <= p["rsi_high"])) | ((df["Close"] >= df["bb_h"]) & (df["Close"].shift(1) < df["bb_h"].shift(1))) | (df["vol_spike"] & (df["Close"] < df["Open"]) & (df["Close"] < df["Close"].shift(1))))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
