"""
Strategy T01739: atr_expansion
Family: atr_expansion
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 8, 'ema_slow': 82, 'atr_period': 18, 'sl_atr': 2.067, 'tp_atr': 2.2805, 'cooldown': 11, 'atr_mult': 2.9888}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["atr_ma"] = df["ATR"].rolling(window=20).mean()
    df["body"] = abs(df["Close"] - df["Open"])
    df["signal"] = 0
    long_cond = uptrend & (df["body"] > p["atr_mult"] * df["atr_ma"]) & (df["Close"] > df["Open"])
    short_cond = downtrend & (df["body"] > p["atr_mult"] * df["atr_ma"]) & (df["Close"] < df["Open"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
