"""
Strategy T11895: heikin_ashi_trend
Family: heikin_ashi_trend
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 12, 'ema_slow': 41, 'atr_period': 15, 'sl_atr': 1.7863, 'tp_atr': 2.6272, 'cooldown': 2, 'session_start': 11, 'session_end': 15}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["ha_close"] = (df["Open"] + df["High"] + df["Low"] + df["Close"]) / 4
    df["ha_open"] = (df["Open"].shift(1) + df["Close"].shift(1)) / 2
    df["signal"] = 0
    long_cond = uptrend & (df["ha_close"] > df["ha_open"]) & (df["ha_close"].shift(1) <= df["ha_open"].shift(1))
    short_cond = downtrend & (df["ha_close"] < df["ha_open"]) & (df["ha_close"].shift(1) >= df["ha_open"].shift(1))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
