"""
Strategy T10428: market_profile
Family: market_profile
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 9, 'ema_slow': 38, 'atr_period': 15, 'sl_atr': 1.9025, 'tp_atr': 2.948, 'cooldown': 6, 'session_start': 12, 'session_end': 20, 'mp_period': 109, 'va_pct': 0.3051}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["poc"] = df["Close"].rolling(window=p["mp_period"]).median()
    df["mp_std"] = df["Close"].rolling(window=p["mp_period"]).std()
    df["va_high"] = df["poc"] + p["va_pct"] * df["mp_std"] * 2
    df["va_low"] = df["poc"] - p["va_pct"] * df["mp_std"] * 2
    df["signal"] = 0
    long_cond = uptrend & (df["Close"] <= df["va_low"]) & (df["Close"] > df["Close"].shift(1)) & (df["Close"] > df["Open"])
    short_cond = downtrend & (df["Close"] >= df["va_high"]) & (df["Close"] < df["Close"].shift(1)) & (df["Close"] < df["Open"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
