"""
Strategy T03705: stoch_rsi
Family: stoch_rsi
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 8, 'ema_slow': 80, 'atr_period': 16, 'sl_atr': 1.8825, 'tp_atr': 3.9829, 'cooldown': 6, 'srsi_period': 13, 'srsi_low': 26, 'srsi_high': 83}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["rsi"] = ta.momentum.rsi(df["Close"], window=p["srsi_period"])
    df["rsi_min"] = df["rsi"].rolling(window=p["srsi_period"]).min()
    df["rsi_max"] = df["rsi"].rolling(window=p["srsi_period"]).max()
    df["stoch_rsi"] = ((df["rsi"] - df["rsi_min"]) / (df["rsi_max"] - df["rsi_min"] + 0.0001)) * 100
    df["signal"] = 0
    long_cond = uptrend & (df["stoch_rsi"] > p["srsi_low"]) & (df["stoch_rsi"].shift(1) <= p["srsi_low"])
    short_cond = downtrend & (df["stoch_rsi"] < p["srsi_high"]) & (df["stoch_rsi"].shift(1) >= p["srsi_high"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
