"""
Strategy T07478: rsi_macd_dual
Family: rsi_macd_dual
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 10, 'ema_slow': 68, 'atr_period': 16, 'sl_atr': 2.3019, 'tp_atr': 3.4319, 'cooldown': 5, 'session_start': 12, 'session_end': 15, 'rsi_period': 13, 'rsi_low': 24, 'rsi_high': 79, 'macd_fast': 13, 'macd_slow': 21, 'macd_sign': 10}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])
    df["macd_h"] = ta.trend.macd_diff(df["Close"], window_slow=p["macd_slow"], window_fast=p["macd_fast"], window_sign=p["macd_sign"])
    df["signal"] = 0
    long_cond = uptrend & (df["rsi"] < p["rsi_low"]) & (df["rsi"].shift(1) >= p["rsi_low"]) & (df["macd_h"] > df["macd_h"].shift(1))
    short_cond = downtrend & (df["rsi"] > p["rsi_high"]) & (df["rsi"].shift(1) <= p["rsi_high"]) & (df["macd_h"] < df["macd_h"].shift(1))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
