"""
Strategy T08244: engulfing_candle
Family: engulfing_candle
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 12, 'ema_slow': 67, 'atr_period': 16, 'sl_atr': 1.8462, 'tp_atr': 2.0051, 'cooldown': 8, 'session_start': 7, 'session_end': 18, 'body_ratio': 1.7413, 'atr_mult': 1.3892}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["body"] = abs(df["Close"] - df["Open"])
    df["prev_body"] = df["body"].shift(1)
    df["bull"] = df["Close"] > df["Open"]
    df["atr_ma"] = df["ATR"].rolling(window=20).mean()
    df["signal"] = 0
    long_cond = uptrend & df["bull"] & (~df["bull"].shift(1).fillna(True)) & (df["body"] > p["body_ratio"] * df["prev_body"]) & (df["ATR"] > p["atr_mult"] * df["atr_ma"])
    short_cond = downtrend & (~df["bull"]) & df["bull"].shift(1).fillna(False) & (df["body"] > p["body_ratio"] * df["prev_body"]) & (df["ATR"] > p["atr_mult"] * df["atr_ma"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
