"""
Strategy T00731: williams_percent_r
Family: williams_percent_r
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 13, 'ema_slow': 62, 'atr_period': 17, 'sl_atr': 1.4651, 'tp_atr': 2.7673, 'wr_period': 12, 'wr_low': -87, 'wr_high': -12}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["wr"] = ta.momentum.williams_r(df["High"], df["Low"], df["Close"], lbp=p["wr_period"])
    df["signal"] = 0
    long_cond = uptrend & (df["wr"] > p["wr_low"]) & (df["wr"].shift(1) <= p["wr_low"])
    short_cond = downtrend & (df["wr"] < p["wr_high"]) & (df["wr"].shift(1) >= p["wr_high"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
