"""
Strategy T00281: dual_rsi
Family: dual_rsi
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 9, 'ema_slow': 77, 'atr_period': 10, 'sl_atr': 1.9573, 'tp_atr': 4.0306, 'rsi_fast': 5, 'rsi_slow': 20}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["rsi_f"] = ta.momentum.rsi(df["Close"], window=p["rsi_fast"])
    df["rsi_s"] = ta.momentum.rsi(df["Close"], window=p["rsi_slow"])
    df["signal"] = 0
    long_cond = uptrend & (df["rsi_f"] > df["rsi_s"]) & (df["rsi_f"].shift(1) <= df["rsi_s"].shift(1)) & (df["rsi_s"] < 50)
    short_cond = downtrend & (df["rsi_f"] < df["rsi_s"]) & (df["rsi_f"].shift(1) >= df["rsi_s"].shift(1)) & (df["rsi_s"] > 50)
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
