"""
Strategy T09865: hybrid_rsi_stoch
Family: hybrid_rsi_stoch
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 10, 'ema_slow': 74, 'atr_period': 19, 'sl_atr': 1.8247, 'tp_atr': 2.3733, 'cooldown': 8, 'session_start': 11, 'session_end': 20, 'rsi_period': 17, 'rsi_low': 32, 'rsi_high': 80, 'stoch_k': 8, 'stoch_d': 5}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])
    df["sk"] = ta.momentum.stoch(df["High"], df["Low"], df["Close"], window=p["stoch_k"], smooth_window=p["stoch_d"])
    df["sd"] = ta.momentum.stoch_signal(df["High"], df["Low"], df["Close"], window=p["stoch_k"], smooth_window=p["stoch_d"])
    df["signal"] = 0
    long_cond = uptrend & (((df["rsi"] < p["rsi_low"]) & (df["rsi"].shift(1) >= p["rsi_low"])) | ((df["sk"] > df["sd"]) & (df["sk"].shift(1) <= df["sd"].shift(1)) & (df["sk"] < 25)))
    short_cond = downtrend & (((df["rsi"] > p["rsi_high"]) & (df["rsi"].shift(1) <= p["rsi_high"])) | ((df["sk"] < df["sd"]) & (df["sk"].shift(1) >= df["sd"].shift(1)) & (df["sk"] > 75)))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
