"""
Strategy T00589: range_trading
Family: range_trading
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 6, 'ema_slow': 84, 'atr_period': 11, 'sl_atr': 1.0234, 'tp_atr': 4.2537, 'range_period': 37, 'range_pct': 0.2492}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["hi_range"] = df["High"].rolling(window=p["range_period"]).max()
    df["lo_range"] = df["Low"].rolling(window=p["range_period"]).min()
    df["rng_width"] = df["hi_range"] - df["lo_range"]
    df["near_low"] = df["Close"] < df["lo_range"] + p["range_pct"] * df["rng_width"]
    df["near_high"] = df["Close"] > df["hi_range"] - p["range_pct"] * df["rng_width"]
    df["signal"] = 0
    long_cond = df["near_low"] & (df["Close"] > df["Open"]) & (df["Close"] > df["Close"].shift(1))
    short_cond = df["near_high"] & (df["Close"] < df["Open"]) & (df["Close"] < df["Close"].shift(1))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
