"""
Strategy T09894: ichimoku_cloud
Family: ichimoku_cloud
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 12, 'ema_slow': 97, 'atr_period': 19, 'sl_atr': 1.5833, 'tp_atr': 2.5, 'cooldown': 5, 'session_start': 7, 'session_end': 21, 'ichi_conv': 12, 'ichi_base': 28, 'ichi_span': 42}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    ichi = ta.trend.IchimokuIndicator(df["High"], df["Low"], window1=p["ichi_conv"], window2=p["ichi_base"], window3=p["ichi_span"])
    df["ichi_a"] = ichi.ichimoku_a()
    df["ichi_b"] = ichi.ichimoku_b()
    df["ichi_conv"] = ichi.ichimoku_conversion_line()
    df["ichi_base"] = ichi.ichimoku_base_line()
    df["above_cloud"] = (df["Close"] > df["ichi_a"]) & (df["Close"] > df["ichi_b"])
    df["below_cloud"] = (df["Close"] < df["ichi_a"]) & (df["Close"] < df["ichi_b"])
    df["signal"] = 0
    long_cond = uptrend & df["above_cloud"] & (df["ichi_conv"] > df["ichi_base"]) & (df["ichi_conv"].shift(1) <= df["ichi_base"].shift(1))
    short_cond = downtrend & df["below_cloud"] & (df["ichi_conv"] < df["ichi_base"]) & (df["ichi_conv"].shift(1) >= df["ichi_base"].shift(1))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
