"""
Strategy T07028: supertrend
Family: supertrend
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 9, 'ema_slow': 81, 'atr_period': 12, 'sl_atr': 1.8227, 'tp_atr': 3.2868, 'cooldown': 5, 'st_mult': 2.6193, 'st_period': 14}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["st_atr"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p["st_period"])
    df["hl2"] = (df["High"] + df["Low"]) / 2
    df["st_upper"] = df["hl2"] + p["st_mult"] * df["st_atr"]
    df["st_lower"] = df["hl2"] - p["st_mult"] * df["st_atr"]
    df["signal"] = 0
    long_cond = uptrend & (df["Close"] > df["st_upper"]) & (df["Close"].shift(1) <= df["st_upper"].shift(1))
    short_cond = downtrend & (df["Close"] < df["st_lower"]) & (df["Close"].shift(1) >= df["st_lower"].shift(1))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
