"""
Strategy T11679: regression_break
Family: regression_break
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 8, 'ema_slow': 73, 'atr_period': 19, 'sl_atr': 1.6696, 'tp_atr': 3.0995, 'cooldown': 3, 'session_start': 8, 'session_end': 21, 'reg_period': 24, 'std_mult': 2.4894}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["reg_mean"] = df["Close"].rolling(window=p["reg_period"]).mean()
    df["reg_std"] = df["Close"].rolling(window=p["reg_period"]).std()
    df["reg_upper"] = df["reg_mean"] + p["std_mult"] * df["reg_std"]
    df["reg_lower"] = df["reg_mean"] - p["std_mult"] * df["reg_std"]
    df["signal"] = 0
    long_cond = uptrend & (df["Close"] <= df["reg_lower"]) & (df["Close"] > df["Close"].shift(1)) & (df["Close"] > df["Open"])
    short_cond = downtrend & (df["Close"] >= df["reg_upper"]) & (df["Close"] < df["Close"].shift(1)) & (df["Close"] < df["Open"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
