"""
Strategy T10301: cci_reversion
Family: cci_reversion
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 12, 'ema_slow': 77, 'atr_period': 14, 'sl_atr': 1.7961, 'tp_atr': 2.5935, 'cooldown': 5, 'session_start': 10, 'session_end': 16, 'cci_period': 11, 'cci_low': -98, 'cci_high': 132}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["cci"] = ta.trend.cci(df["High"], df["Low"], df["Close"], window=p["cci_period"])
    df["signal"] = 0
    long_cond = uptrend & (df["cci"] > p["cci_low"]) & (df["cci"].shift(1) <= p["cci_low"]) & (df["Close"] > df["Open"])
    short_cond = downtrend & (df["cci"] < p["cci_high"]) & (df["cci"].shift(1) >= p["cci_high"]) & (df["Close"] < df["Open"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
