"""
Strategy T00639: stochastic_cross
Family: stochastic_cross
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 8, 'ema_slow': 97, 'atr_period': 10, 'sl_atr': 2.283, 'tp_atr': 2.2886, 'stoch_k': 8, 'stoch_d': 6, 'stoch_low': 27, 'stoch_high': 75}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["sk"] = ta.momentum.stoch(df["High"], df["Low"], df["Close"], window=p["stoch_k"], smooth_window=p["stoch_d"])
    df["sd"] = ta.momentum.stoch_signal(df["High"], df["Low"], df["Close"], window=p["stoch_k"], smooth_window=p["stoch_d"])
    df["signal"] = 0
    long_cond = uptrend & (df["sk"] > df["sd"]) & (df["sk"].shift(1) <= df["sd"].shift(1)) & (df["sk"].shift(1) < p["stoch_low"])
    short_cond = downtrend & (df["sk"] < df["sd"]) & (df["sk"].shift(1) >= df["sd"].shift(1)) & (df["sk"].shift(1) > p["stoch_high"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
