"""
Strategy T09191: three_soldiers
Family: three_soldiers
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 11, 'ema_slow': 39, 'atr_period': 20, 'sl_atr': 2.4608, 'tp_atr': 3.2327, 'cooldown': 6, 'session_start': 11, 'session_end': 20, 'min_body_atr': 0.6786}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["body"] = abs(df["Close"] - df["Open"])
    df["bull"] = (df["Close"] > df["Open"]).astype(int)
    df["bear"] = (df["Close"] < df["Open"]).astype(int)
    df["three_bull"] = (df["bull"] + df["bull"].shift(1) + df["bull"].shift(2)) == 3
    df["three_bear"] = (df["bear"] + df["bear"].shift(1) + df["bear"].shift(2)) == 3
    df["rising"] = (df["Close"] > df["Close"].shift(1)) & (df["Close"].shift(1) > df["Close"].shift(2))
    df["falling"] = (df["Close"] < df["Close"].shift(1)) & (df["Close"].shift(1) < df["Close"].shift(2))
    df["body_ok"] = df["body"] > p["min_body_atr"] * df["ATR"]
    df["signal"] = 0
    long_cond = uptrend & df["three_bull"] & df["rising"] & df["body_ok"]
    short_cond = downtrend & df["three_bear"] & df["falling"] & df["body_ok"]
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
