"""
Strategy T00492: atr_expansion
Family: atr_expansion
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 7, 'ema_slow': 92, 'atr_period': 11, 'sl_atr': 2.3404, 'tp_atr': 4.0291, 'atr_mult': 2.5147}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["atr_ma"] = df["ATR"].rolling(window=20).mean()
    df["body"] = abs(df["Close"] - df["Open"])
    df["signal"] = 0
    long_cond = uptrend & (df["body"] > p["atr_mult"] * df["atr_ma"]) & (df["Close"] > df["Open"])
    short_cond = downtrend & (df["body"] > p["atr_mult"] * df["atr_ma"]) & (df["Close"] < df["Open"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
