"""
Strategy T00616: ichimoku_cloud
Family: ichimoku_cloud
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 10, 'ema_slow': 44, 'atr_period': 15, 'sl_atr': 1.0239, 'tp_atr': 2.7227, 'ichi_conv': 8, 'ichi_base': 25, 'ichi_span': 51}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    ichi = ta.trend.IchimokuIndicator(df["High"], df["Low"], window1=p["ichi_conv"], window2=p["ichi_base"], window3=p["ichi_span"])
    df["ichi_a"] = ichi.ichimoku_a()
    df["ichi_b"] = ichi.ichimoku_b()
    df["ichi_conv"] = ichi.ichimoku_conversion_line()
    df["ichi_base"] = ichi.ichimoku_base_line()
    df["signal"] = 0
    long_cond = (df["Close"] > df["ichi_a"]) & (df["Close"] > df["ichi_b"]) & (df["ichi_conv"] > df["ichi_base"]) & (df["ichi_conv"].shift(1) <= df["ichi_base"].shift(1))
    short_cond = (df["Close"] < df["ichi_a"]) & (df["Close"] < df["ichi_b"]) & (df["ichi_conv"] < df["ichi_base"]) & (df["ichi_conv"].shift(1) >= df["ichi_base"].shift(1))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
