"""
Strategy T00341: keltner_breakout
Family: keltner_breakout
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 15, 'ema_slow': 45, 'atr_period': 10, 'sl_atr': 2.3165, 'tp_atr': 2.4353, 'kc_period': 28, 'kc_mult': 2.3229}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["kc_mid"] = ta.trend.ema_indicator(df["Close"], window=p["kc_period"])
    df["kc_atr"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p["kc_period"])
    df["kc_h"] = df["kc_mid"] + p["kc_mult"] * df["kc_atr"]
    df["kc_l"] = df["kc_mid"] - p["kc_mult"] * df["kc_atr"]
    df["signal"] = 0
    long_cond = uptrend & (df["Close"] > df["kc_h"]) & (df["Close"].shift(1) <= df["kc_h"].shift(1))
    short_cond = downtrend & (df["Close"] < df["kc_l"]) & (df["Close"].shift(1) >= df["kc_l"].shift(1))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
