"""
Strategy T00225: adx_breakout
Family: adx_breakout
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 12, 'ema_slow': 45, 'atr_period': 10, 'sl_atr': 1.1034, 'tp_atr': 3.9683, 'adx_period': 20, 'adx_thresh': 31}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["adx_val"] = ta.trend.adx(df["High"], df["Low"], df["Close"], window=p["adx_period"])
    df["di_p"] = ta.trend.adx_pos(df["High"], df["Low"], df["Close"], window=p["adx_period"])
    df["di_n"] = ta.trend.adx_neg(df["High"], df["Low"], df["Close"], window=p["adx_period"])
    df["signal"] = 0
    long_cond = (df["adx_val"] > p["adx_thresh"]) & (df["di_p"] > df["di_n"]) & (df["di_p"].shift(1) <= df["di_n"].shift(1))
    short_cond = (df["adx_val"] > p["adx_thresh"]) & (df["di_n"] > df["di_p"]) & (df["di_n"].shift(1) <= df["di_p"].shift(1))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
