"""
Strategy T00653: hybrid_supertrend_rsi
Family: hybrid_supertrend_rsi
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 11, 'ema_slow': 46, 'atr_period': 13, 'sl_atr': 1.4813, 'tp_atr': 2.25, 'st_mult': 2.9824, 'st_period': 8, 'rsi_period': 12, 'rsi_low': 20, 'rsi_high': 60}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["st_atr"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p["st_period"])
    df["hl2"] = (df["High"] + df["Low"]) / 2
    df["st_upper"] = df["hl2"] + p["st_mult"] * df["st_atr"]
    df["st_lower"] = df["hl2"] - p["st_mult"] * df["st_atr"]
    df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])
    df["signal"] = 0
    long_cond = uptrend & (((df["Close"] > df["st_upper"]) & (df["Close"].shift(1) <= df["st_upper"].shift(1))) | (df["rsi"] < p["rsi_low"]))
    short_cond = downtrend & (((df["Close"] < df["st_lower"]) & (df["Close"].shift(1) >= df["st_lower"].shift(1))) | (df["rsi"] > p["rsi_high"]))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
