"""
Strategy T00698: parabolic_sar
Family: parabolic_sar
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 11, 'ema_slow': 86, 'atr_period': 14, 'sl_atr': 2.0031, 'tp_atr': 2.0674}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    psar_ind = ta.trend.PSARIndicator(df["High"], df["Low"], df["Close"])
    df["psar_up"] = psar_ind.psar_up()
    df["psar_down"] = psar_ind.psar_down()
    df["signal"] = 0
    long_cond = uptrend & df["psar_up"].notna() & df["psar_up"].shift(1).isna()
    short_cond = downtrend & df["psar_down"].notna() & df["psar_down"].shift(1).isna()
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
