"""
Strategy T00211: ema_bounce
Family: ema_bounce
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 12, 'ema_slow': 43, 'atr_period': 17, 'sl_atr': 2.2769, 'tp_atr': 3.0682, 'ema_mid': 19}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["ema_m"] = ta.trend.ema_indicator(df["Close"], window=p["ema_mid"])
    df["signal"] = 0
    long_cond = uptrend & (df["Low"] <= df["ema_m"]) & (df["Close"] > df["ema_m"]) & (df["Close"] > df["Open"])
    short_cond = downtrend & (df["High"] >= df["ema_m"]) & (df["Close"] < df["ema_m"]) & (df["Close"] < df["Open"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
