"""
Strategy T10359: squeeze_momentum
Family: squeeze_momentum
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 11, 'ema_slow': 48, 'atr_period': 10, 'sl_atr': 1.8121, 'tp_atr': 3.2403, 'cooldown': 5, 'session_start': 12, 'session_end': 18, 'bb_period': 15, 'bb_std': 1.5385, 'kc_period': 22, 'kc_mult': 1.239}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["bb_h"] = ta.volatility.bollinger_hband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])
    df["bb_l"] = ta.volatility.bollinger_lband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])
    df["kc_mid"] = ta.trend.ema_indicator(df["Close"], window=p["kc_period"])
    df["kc_atr"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p["kc_period"])
    df["kc_h"] = df["kc_mid"] + p["kc_mult"] * df["kc_atr"]
    df["kc_l"] = df["kc_mid"] - p["kc_mult"] * df["kc_atr"]
    df["in_squeeze"] = (df["bb_l"] > df["kc_l"]) & (df["bb_h"] < df["kc_h"])
    df["was_squeeze"] = df["in_squeeze"].shift(1).fillna(False)
    df["mom"] = df["Close"] - ta.trend.ema_indicator(df["Close"], window=p["bb_period"])
    df["signal"] = 0
    long_cond = uptrend & df["was_squeeze"] & ~df["in_squeeze"] & (df["mom"] > 0) & (df["mom"] > df["mom"].shift(1))
    short_cond = downtrend & df["was_squeeze"] & ~df["in_squeeze"] & (df["mom"] < 0) & (df["mom"] < df["mom"].shift(1))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
