"""
Strategy T00374: rsi_pin_bar
Family: rsi_pin_bar
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 8, 'ema_slow': 98, 'atr_period': 17, 'sl_atr': 1.0173, 'tp_atr': 4.2565, 'rsi_period': 20, 'rsi_low': 23, 'rsi_high': 77, 'wick_ratio': 2.8004}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])
    df["body"] = abs(df["Close"] - df["Open"]).clip(lower=0.01)
    df["lo_wick"] = df[["Close", "Open"]].min(axis=1) - df["Low"]
    df["hi_wick"] = df["High"] - df[["Close", "Open"]].max(axis=1)
    df["signal"] = 0
    long_cond = uptrend & (df["rsi"] < p["rsi_low"]) & (df["lo_wick"] > p["wick_ratio"] * df["body"]) & (df["Close"] > df["Open"])
    short_cond = downtrend & (df["rsi"] > p["rsi_high"]) & (df["hi_wick"] > p["wick_ratio"] * df["body"]) & (df["Close"] < df["Open"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
