"""
Strategy T00477: macd_histogram
Family: macd_histogram
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 6, 'ema_slow': 67, 'atr_period': 19, 'sl_atr': 1.7757, 'tp_atr': 3.604, 'macd_fast': 10, 'macd_slow': 27, 'macd_sign': 9}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["macd_h"] = ta.trend.macd_diff(df["Close"], window_slow=p["macd_slow"], window_fast=p["macd_fast"], window_sign=p["macd_sign"])
    df["signal"] = 0
    long_cond = uptrend & (df["macd_h"] > 0) & (df["macd_h"].shift(1) <= 0)
    short_cond = downtrend & (df["macd_h"] < 0) & (df["macd_h"].shift(1) >= 0)
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
