"""
Strategy T07096: liquidity_sweep
Family: liquidity_sweep
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 6, 'ema_slow': 94, 'atr_period': 14, 'sl_atr': 2.1948, 'tp_atr': 3.7709, 'cooldown': 4, 'sweep_lookback': 10, 'wick_min': 1.0036}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["prev_lo"] = df["Low"].rolling(window=p["sweep_lookback"]).min().shift(1)
    df["prev_hi"] = df["High"].rolling(window=p["sweep_lookback"]).max().shift(1)
    df["lo_wick"] = df[["Close", "Open"]].min(axis=1) - df["Low"]
    df["hi_wick"] = df["High"] - df[["Close", "Open"]].max(axis=1)
    df["swept_lo"] = (df["Low"] < df["prev_lo"]) & (df["Close"] > df["prev_lo"])
    df["swept_hi"] = (df["High"] > df["prev_hi"]) & (df["Close"] < df["prev_hi"])
    df["signal"] = 0
    long_cond = uptrend & df["swept_lo"] & (df["lo_wick"] > p["wick_min"] * df["ATR"]) & (df["Close"] > df["Open"])
    short_cond = downtrend & df["swept_hi"] & (df["hi_wick"] > p["wick_min"] * df["ATR"]) & (df["Close"] < df["Open"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
