"""
Strategy T02355: donchian_pullback
Family: donchian_pullback
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 12, 'ema_slow': 95, 'atr_period': 15, 'sl_atr': 1.7906, 'tp_atr': 3.8673, 'cooldown': 11, 'dc_period': 25}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["dc_h"] = df["High"].rolling(window=p["dc_period"]).max().shift(1)
    df["dc_l"] = df["Low"].rolling(window=p["dc_period"]).min().shift(1)
    df["dc_mid"] = (df["dc_h"] + df["dc_l"]) / 2
    df["signal"] = 0
    long_cond = uptrend & (df["Low"] <= df["dc_mid"]) & (df["Close"] > df["dc_mid"]) & (df["Close"] > df["Open"])
    short_cond = downtrend & (df["High"] >= df["dc_mid"]) & (df["Close"] < df["dc_mid"]) & (df["Close"] < df["Open"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
