"""
Strategy T04912: hybrid_triple_or
Family: hybrid_triple_or
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 7, 'ema_slow': 71, 'atr_period': 11, 'sl_atr': 1.5939, 'tp_atr': 3.4552, 'cooldown': 12, 'rsi_period': 17, 'rsi_low': 40, 'rsi_high': 68, 'macd_fast': 15, 'macd_slow': 20, 'macd_sign': 8, 'atr_ratio': 1.8419}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])
    df["macd_h"] = ta.trend.macd_diff(df["Close"], window_slow=p["macd_slow"], window_fast=p["macd_fast"], window_sign=p["macd_sign"])
    df["atr_ma"] = df["ATR"].rolling(window=20).mean()
    df["atr_exp"] = df["ATR"] > p["atr_ratio"] * df["atr_ma"]
    df["signal"] = 0
    long_cond = uptrend & (((df["rsi"] < p["rsi_low"]) & (df["rsi"].shift(1) >= p["rsi_low"])) | ((df["macd_h"] > 0) & (df["macd_h"].shift(1) <= 0)) | (df["atr_exp"] & (~df["atr_exp"].shift(1).fillna(False)) & (df["Close"] > df["Open"])))
    short_cond = downtrend & (((df["rsi"] > p["rsi_high"]) & (df["rsi"].shift(1) <= p["rsi_high"])) | ((df["macd_h"] < 0) & (df["macd_h"].shift(1) >= 0)) | (df["atr_exp"] & (~df["atr_exp"].shift(1).fillna(False)) & (df["Close"] < df["Open"])))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
