"""
Strategy T00796: fibonacci_retrace
Family: fibonacci_retrace
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 13, 'ema_slow': 75, 'atr_period': 12, 'sl_atr': 1.5472, 'tp_atr': 3.6599, 'fib_lookback': 52, 'fib_level': 0.6233}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["swing_h"] = df["High"].rolling(window=p["fib_lookback"]).max()
    df["swing_l"] = df["Low"].rolling(window=p["fib_lookback"]).min()
    df["fib_buy"] = df["swing_h"] - p["fib_level"] * (df["swing_h"] - df["swing_l"])
    df["fib_sell"] = df["swing_l"] + p["fib_level"] * (df["swing_h"] - df["swing_l"])
    df["signal"] = 0
    long_cond = uptrend & (df["Low"] <= df["fib_buy"]) & (df["Close"] > df["fib_buy"]) & (df["Close"] > df["Open"])
    short_cond = downtrend & (df["High"] >= df["fib_sell"]) & (df["Close"] < df["fib_sell"]) & (df["Close"] < df["Open"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
