"""
Strategy T06493: london_open
Family: london_open
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 6, 'ema_slow': 77, 'atr_period': 14, 'sl_atr': 2.1346, 'tp_atr': 2.2729, 'cooldown': 6, 'pre_bars': 11, 'atr_filter': 1.4658}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["hour"] = pd.to_datetime(df["time"]).dt.hour
    df["london"] = (df["hour"] >= 8) & (df["hour"] <= 10)
    df["pre_hi"] = df["High"].rolling(window=p["pre_bars"]).max().shift(1)
    df["pre_lo"] = df["Low"].rolling(window=p["pre_bars"]).min().shift(1)
    df["atr_ma"] = df["ATR"].rolling(window=20).mean()
    df["vol_ok"] = df["ATR"] > p["atr_filter"] * df["atr_ma"]
    df["signal"] = 0
    long_cond = uptrend & df["london"] & df["vol_ok"] & (df["Close"] > df["pre_hi"]) & (df["Close"].shift(1) <= df["pre_hi"].shift(1))
    short_cond = downtrend & df["london"] & df["vol_ok"] & (df["Close"] < df["pre_lo"]) & (df["Close"].shift(1) >= df["pre_lo"].shift(1))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
