"""
Strategy T10868: adx_breakout
Family: adx_breakout
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 8, 'ema_slow': 59, 'atr_period': 16, 'sl_atr': 2.224, 'tp_atr': 3.949, 'cooldown': 4, 'session_start': 7, 'session_end': 18, 'adx_period': 13, 'adx_thresh': 34}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["adx_val"] = ta.trend.adx(df["High"], df["Low"], df["Close"], window=p["adx_period"])
    df["di_p"] = ta.trend.adx_pos(df["High"], df["Low"], df["Close"], window=p["adx_period"])
    df["di_n"] = ta.trend.adx_neg(df["High"], df["Low"], df["Close"], window=p["adx_period"])
    df["signal"] = 0
    long_cond = (df["adx_val"] > p["adx_thresh"]) & (df["di_p"] > df["di_n"]) & (df["di_p"].shift(1) <= df["di_n"].shift(1))
    short_cond = (df["adx_val"] > p["adx_thresh"]) & (df["di_n"] > df["di_p"]) & (df["di_n"].shift(1) <= df["di_p"].shift(1))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
