"""
Strategy T00643: hybrid_triple_or
Family: hybrid_triple_or
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 7, 'ema_slow': 66, 'atr_period': 14, 'sl_atr': 1.3875, 'tp_atr': 2.6224, 'rsi_period': 21, 'rsi_low': 24, 'rsi_high': 76, 'macd_fast': 9, 'macd_slow': 20, 'macd_sign': 11, 'atr_ratio': 1.4512}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])
    df["macd_h"] = ta.trend.macd_diff(df["Close"], window_slow=p["macd_slow"], window_fast=p["macd_fast"], window_sign=p["macd_sign"])
    df["atr_ma"] = df["ATR"].rolling(window=20).mean()
    df["atr_exp"] = df["ATR"] > p["atr_ratio"] * df["atr_ma"]
    df["signal"] = 0
    long_cond = uptrend & ((df["rsi"] < p["rsi_low"]) | ((df["macd_h"] > 0) & (df["macd_h"].shift(1) <= 0)) | (df["atr_exp"] & (df["Close"] > df["Open"])))
    short_cond = downtrend & ((df["rsi"] > p["rsi_high"]) | ((df["macd_h"] < 0) & (df["macd_h"].shift(1) >= 0)) | (df["atr_exp"] & (df["Close"] < df["Open"])))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
