"""
Strategy T10661: support_resistance
Family: support_resistance
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 9, 'ema_slow': 44, 'atr_period': 17, 'sl_atr': 2.3932, 'tp_atr': 2.3871, 'cooldown': 6, 'session_start': 12, 'session_end': 21, 'sr_lookback': 30}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["resistance"] = df["High"].rolling(window=p["sr_lookback"]).max().shift(1)
    df["support"] = df["Low"].rolling(window=p["sr_lookback"]).min().shift(1)
    df["signal"] = 0
    long_cond = uptrend & (df["Low"] <= df["support"] * 1.001) & (df["Close"] > df["support"]) & (df["Close"] > df["Open"])
    short_cond = downtrend & (df["High"] >= df["resistance"] * 0.999) & (df["Close"] < df["resistance"]) & (df["Close"] < df["Open"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
