"""
Strategy T00792: hybrid_macd_bb
Family: hybrid_macd_bb
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 5, 'ema_slow': 75, 'atr_period': 16, 'sl_atr': 1.2515, 'tp_atr': 3.6091, 'macd_fast': 14, 'macd_slow': 25, 'macd_sign': 12, 'bb_period': 26, 'bb_std': 2.85}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["macd_h"] = ta.trend.macd_diff(df["Close"], window_slow=p["macd_slow"], window_fast=p["macd_fast"], window_sign=p["macd_sign"])
    df["bb_h"] = ta.volatility.bollinger_hband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])
    df["bb_l"] = ta.volatility.bollinger_lband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])
    df["signal"] = 0
    long_cond = uptrend & (((df["macd_h"] > 0) & (df["macd_h"].shift(1) <= 0)) | (df["Close"] <= df["bb_l"]))
    short_cond = downtrend & (((df["macd_h"] < 0) & (df["macd_h"].shift(1) >= 0)) | (df["Close"] >= df["bb_h"]))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
