"""
Strategy T00675: volume_spike
Family: volume_spike
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 12, 'ema_slow': 88, 'atr_period': 11, 'sl_atr': 1.8589, 'tp_atr': 4.3623, 'vol_mult': 2.3913}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["vol_ma"] = df["Volume"].rolling(window=20).mean()
    df["vol_spike"] = df["Volume"] > p["vol_mult"] * df["vol_ma"]
    df["signal"] = 0
    long_cond = uptrend & df["vol_spike"] & (df["Close"] > df["Open"]) & (df["Close"] > df["Close"].shift(1))
    short_cond = downtrend & df["vol_spike"] & (df["Close"] < df["Open"]) & (df["Close"] < df["Close"].shift(1))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
