"""
Strategy T02166: price_action_doji
Family: price_action_doji
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 9, 'ema_slow': 56, 'atr_period': 10, 'sl_atr': 1.7962, 'tp_atr': 3.5751, 'cooldown': 10, 'doji_ratio': 0.2433, 'confirm_ratio': 1.01}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["body"] = abs(df["Close"] - df["Open"])
    df["candle_range"] = (df["High"] - df["Low"]).clip(lower=0.01)
    df["is_doji"] = df["body"] < p["doji_ratio"] * df["candle_range"]
    df["prev_doji"] = df["is_doji"].shift(1).fillna(False)
    df["confirm_bull"] = (df["Close"] > df["Open"]) & (df["body"] > p["confirm_ratio"] * df["body"].shift(1).clip(lower=0.01))
    df["confirm_bear"] = (df["Close"] < df["Open"]) & (df["body"] > p["confirm_ratio"] * df["body"].shift(1).clip(lower=0.01))
    df["signal"] = 0
    long_cond = uptrend & df["prev_doji"] & df["confirm_bull"]
    short_cond = downtrend & df["prev_doji"] & df["confirm_bear"]
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
