"""
Strategy T08318: vwap_deviation
Family: vwap_deviation
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 14, 'ema_slow': 50, 'atr_period': 17, 'sl_atr': 2.098, 'tp_atr': 3.6935, 'cooldown': 6, 'session_start': 12, 'session_end': 16, 'vwap_period': 38, 'vwap_std': 1.563}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["typical"] = (df["High"] + df["Low"] + df["Close"]) / 3
    df["vwap"] = (df["typical"] * df["Volume"]).rolling(window=p["vwap_period"]).sum() / df["Volume"].rolling(window=p["vwap_period"]).sum().clip(lower=1)
    df["vwap_sd"] = df["typical"].rolling(window=p["vwap_period"]).std()
    df["vwap_lo"] = df["vwap"] - p["vwap_std"] * df["vwap_sd"]
    df["vwap_hi"] = df["vwap"] + p["vwap_std"] * df["vwap_sd"]
    df["signal"] = 0
    long_cond = uptrend & (df["Close"] <= df["vwap_lo"]) & (df["Close"] > df["Close"].shift(1))
    short_cond = downtrend & (df["Close"] >= df["vwap_hi"]) & (df["Close"] < df["Close"].shift(1))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
