"""
Strategy T04777: rsi_divergence
Family: rsi_divergence
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 5, 'ema_slow': 55, 'atr_period': 10, 'sl_atr': 2.3487, 'tp_atr': 2.2312, 'cooldown': 10, 'rsi_period': 9, 'div_lookback': 13}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])
    df["price_lo"] = df["Close"].rolling(window=p["div_lookback"]).min()
    df["rsi_lo"] = df["rsi"].rolling(window=p["div_lookback"]).min()
    df["price_hi"] = df["Close"].rolling(window=p["div_lookback"]).max()
    df["rsi_hi"] = df["rsi"].rolling(window=p["div_lookback"]).max()
    df["bull_div"] = (df["Close"] <= df["price_lo"] * 1.001) & (df["rsi"] > df["rsi_lo"] + 5)
    df["bear_div"] = (df["Close"] >= df["price_hi"] * 0.999) & (df["rsi"] < df["rsi_hi"] - 5)
    df["signal"] = 0
    long_cond = uptrend & df["bull_div"] & (df["Close"] > df["Open"])
    short_cond = downtrend & df["bear_div"] & (df["Close"] < df["Open"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
