"""
Strategy T11333: hybrid_2of3
Family: hybrid_2of3
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 8, 'ema_slow': 53, 'atr_period': 15, 'sl_atr': 1.6795, 'tp_atr': 3.1469, 'cooldown': 3, 'session_start': 7, 'session_end': 21, 'stoch_k': 8, 'stoch_d': 7, 'macd_fast': 13, 'macd_slow': 25, 'macd_sign': 8, 'ema_mid': 28}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["sk"] = ta.momentum.stoch(df["High"], df["Low"], df["Close"], window=p["stoch_k"], smooth_window=p["stoch_d"])
    df["macd_h"] = ta.trend.macd_diff(df["Close"], window_slow=p["macd_slow"], window_fast=p["macd_fast"], window_sign=p["macd_sign"])
    df["ema_m"] = ta.trend.ema_indicator(df["Close"], window=p["ema_mid"])
    df["c_stoch_l"] = (df["sk"] < 25).astype(int)
    df["c_macd_l"] = ((df["macd_h"] > 0) & (df["macd_h"].shift(1) <= 0)).astype(int)
    df["c_ema_l"] = ((df["Low"] <= df["ema_m"]) & (df["Close"] > df["ema_m"])).astype(int)
    df["score_l"] = df["c_stoch_l"] + df["c_macd_l"] + df["c_ema_l"]
    df["c_stoch_s"] = (df["sk"] > 75).astype(int)
    df["c_macd_s"] = ((df["macd_h"] < 0) & (df["macd_h"].shift(1) >= 0)).astype(int)
    df["c_ema_s"] = ((df["High"] >= df["ema_m"]) & (df["Close"] < df["ema_m"])).astype(int)
    df["score_s"] = df["c_stoch_s"] + df["c_macd_s"] + df["c_ema_s"]
    df["signal"] = 0
    long_cond = uptrend & (df["score_l"] >= 2)
    short_cond = downtrend & (df["score_s"] >= 2)
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
