"""
Strategy T07587: triple_ema_pullback
Family: triple_ema_pullback
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 6, 'ema_slow': 39, 'atr_period': 18, 'sl_atr': 2.1708, 'tp_atr': 2.2996, 'cooldown': 5, 'session_start': 8, 'session_end': 19, 'ema_1': 5, 'ema_2': 20, 'ema_3': 58}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["e1"] = ta.trend.ema_indicator(df["Close"], window=p["ema_1"])
    df["e2"] = ta.trend.ema_indicator(df["Close"], window=p["ema_2"])
    df["e3"] = ta.trend.ema_indicator(df["Close"], window=p["ema_3"])
    df["signal"] = 0
    long_cond = (df["e1"] > df["e2"]) & (df["e2"] > df["e3"]) & (df["Low"] <= df["e2"]) & (df["Close"] > df["e2"])
    short_cond = (df["e1"] < df["e2"]) & (df["e2"] < df["e3"]) & (df["High"] >= df["e2"]) & (df["Close"] < df["e2"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
