"""
Strategy T10637: bb_squeeze
Family: bb_squeeze
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 6, 'ema_slow': 79, 'atr_period': 20, 'sl_atr': 2.112, 'tp_atr': 3.3222, 'cooldown': 5, 'session_start': 9, 'session_end': 19, 'bb_period': 21, 'bb_std': 2.5859, 'sq_pct': 0.6216}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["bb_w"] = ta.volatility.bollinger_wband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])
    df["bb_w_ma"] = df["bb_w"].rolling(window=50).mean()
    df["squeeze"] = df["bb_w"] < p["sq_pct"] * df["bb_w_ma"]
    df["was_sq"] = df["squeeze"].shift(1).fillna(False)
    df["bb_h"] = ta.volatility.bollinger_hband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])
    df["bb_l"] = ta.volatility.bollinger_lband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])
    df["signal"] = 0
    long_cond = uptrend & df["was_sq"] & ~df["squeeze"] & (df["Close"] > df["bb_h"])
    short_cond = downtrend & df["was_sq"] & ~df["squeeze"] & (df["Close"] < df["bb_l"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
