"""
Strategy T11307: session_breakout
Family: session_breakout
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 7, 'ema_slow': 53, 'atr_period': 13, 'sl_atr': 1.7231, 'tp_atr': 3.6818, 'cooldown': 2, 'session_start': 11, 'session_end': 18, 'range_bars': 15}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["hour"] = pd.to_datetime(df["time"]).dt.hour
    df["in_session"] = (df["hour"] >= 8) & (df["hour"] <= 16)
    df["range_hi"] = df["High"].rolling(window=p["range_bars"]).max().shift(1)
    df["range_lo"] = df["Low"].rolling(window=p["range_bars"]).min().shift(1)
    df["signal"] = 0
    long_cond = uptrend & df["in_session"] & (df["Close"] > df["range_hi"]) & (df["Close"].shift(1) <= df["range_hi"].shift(1))
    short_cond = downtrend & df["in_session"] & (df["Close"] < df["range_lo"]) & (df["Close"].shift(1) >= df["range_lo"].shift(1))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
