"""
Strategy T09390: hammer_star
Family: hammer_star
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 7, 'ema_slow': 47, 'atr_period': 13, 'sl_atr': 2.1367, 'tp_atr': 3.1942, 'cooldown': 7, 'session_start': 11, 'session_end': 18, 'wick_mult': 2.9487, 'body_max_pct': 0.3353}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["body"] = abs(df["Close"] - df["Open"]).clip(lower=0.01)
    df["full_range"] = (df["High"] - df["Low"]).clip(lower=0.01)
    df["lo_wick"] = df[["Close", "Open"]].min(axis=1) - df["Low"]
    df["hi_wick"] = df["High"] - df[["Close", "Open"]].max(axis=1)
    df["body_pct"] = df["body"] / df["full_range"]
    df["signal"] = 0
    long_cond = uptrend & (df["lo_wick"] > p["wick_mult"] * df["body"]) & (df["body_pct"] < p["body_max_pct"]) & (df["Close"] > df["Open"])
    short_cond = downtrend & (df["hi_wick"] > p["wick_mult"] * df["body"]) & (df["body_pct"] < p["body_max_pct"]) & (df["Close"] < df["Open"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
