"""
Strategy T11572: obv_divergence
Family: obv_divergence
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 9, 'ema_slow': 51, 'atr_period': 14, 'sl_atr': 2.0733, 'tp_atr': 3.0416, 'cooldown': 5, 'session_start': 12, 'session_end': 15, 'obv_ema': 28, 'lookback': 19}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["obv"] = (np.sign(df["Close"].diff()) * df["Volume"]).cumsum()
    df["obv_ema"] = ta.trend.ema_indicator(df["obv"], window=p["obv_ema"])
    df["price_rising"] = df["Close"] > df["Close"].shift(p["lookback"])
    df["obv_rising"] = df["obv_ema"] > df["obv_ema"].shift(p["lookback"])
    df["signal"] = 0
    long_cond = uptrend & (~df["price_rising"]) & df["obv_rising"] & (df["Close"] > df["Open"])
    short_cond = downtrend & df["price_rising"] & (~df["obv_rising"]) & (df["Close"] < df["Open"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
