"""
Strategy T00781: trend_reversal
Family: trend_reversal
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {
    "ema_fast": 10,
    "ema_slow": 50,
    "atr_period": 21,
    "sl_atr": 1.3118,
    "tp_atr": 2.6833,
    "rsi_period": 25,
    "rsi_low": 28,
    "rsi_high": 55,
    "consec_bars": 8
}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])
    df["down_count"] = (df["Close"] < df["Close"].shift(1)).rolling(window=p["consec_bars"]).sum()
    df["up_count"] = (df["Close"] > df["Close"].shift(1)).rolling(window=p["consec_bars"]).sum()
    df["signal"] = 0
    long_cond = (df["down_count"] >= p["consec_bars"]) & (df["rsi"] < p["rsi_low"]) & (df["Close"] > df["Open"])
    short_cond = (df["up_count"] >= p["consec_bars"]) & (df["rsi"] > p["rsi_high"]) & (df["Close"] < df["Open"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
