"""
Strategy T11316: macd_line_cross
Family: macd_line_cross
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 6, 'ema_slow': 38, 'atr_period': 16, 'sl_atr': 2.1191, 'tp_atr': 3.6899, 'cooldown': 3, 'session_start': 10, 'session_end': 21, 'macd_fast': 14, 'macd_slow': 25, 'macd_sign': 11}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["macd_l"] = ta.trend.macd(df["Close"], window_slow=p["macd_slow"], window_fast=p["macd_fast"])
    df["macd_sig"] = ta.trend.macd_signal(df["Close"], window_slow=p["macd_slow"], window_fast=p["macd_fast"], window_sign=p["macd_sign"])
    df["signal"] = 0
    long_cond = uptrend & (df["macd_l"] > df["macd_sig"]) & (df["macd_l"].shift(1) <= df["macd_sig"].shift(1))
    short_cond = downtrend & (df["macd_l"] < df["macd_sig"]) & (df["macd_l"].shift(1) >= df["macd_sig"].shift(1))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
