"""
Strategy T00645: engulfing_candle
Family: engulfing_candle
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 10, 'ema_slow': 39, 'atr_period': 20, 'sl_atr': 1.2159, 'tp_atr': 2.9248, 'body_ratio': 1.9525}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["body"] = abs(df["Close"] - df["Open"])
    df["prev_body"] = df["body"].shift(1)
    df["bull"] = df["Close"] > df["Open"]
    df["signal"] = 0
    long_cond = uptrend & df["bull"] & (~df["bull"].shift(1).fillna(True)) & (df["body"] > p["body_ratio"] * df["prev_body"])
    short_cond = downtrend & (~df["bull"]) & df["bull"].shift(1).fillna(False) & (df["body"] > p["body_ratio"] * df["prev_body"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
