"""
Strategy T02854: trend_reversal
Family: trend_reversal
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 5, 'ema_slow': 36, 'atr_period': 15, 'sl_atr': 2.434, 'tp_atr': 2.442, 'cooldown': 12, 'rsi_period': 12, 'rsi_low': 38, 'rsi_high': 62, 'consec_bars': 5}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])
    df["down_count"] = (df["Close"] < df["Close"].shift(1)).rolling(window=p["consec_bars"]).sum()
    df["up_count"] = (df["Close"] > df["Close"].shift(1)).rolling(window=p["consec_bars"]).sum()
    df["signal"] = 0
    long_cond = uptrend & (df["down_count"] >= p["consec_bars"]) & (df["rsi"] < p["rsi_low"]) & (df["Close"] > df["Open"])
    short_cond = downtrend & (df["up_count"] >= p["consec_bars"]) & (df["rsi"] > p["rsi_high"]) & (df["Close"] < df["Open"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
