"""
Strategy T05815: bollinger_breakout
Family: bollinger_breakout
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 5, 'ema_slow': 59, 'atr_period': 20, 'sl_atr': 2.0035, 'tp_atr': 3.3962, 'cooldown': 7, 'bb_period': 30, 'bb_std': 2.942}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["bb_h"] = ta.volatility.bollinger_hband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])
    df["bb_l"] = ta.volatility.bollinger_lband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])
    df["signal"] = 0
    long_cond = uptrend & (df["Close"] > df["bb_h"]) & (df["Close"].shift(1) <= df["bb_h"].shift(1))
    short_cond = downtrend & (df["Close"] < df["bb_l"]) & (df["Close"].shift(1) >= df["bb_l"].shift(1))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
wn:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
