"""
Strategy T10406: range_trading
Family: range_trading
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 14, 'ema_slow': 98, 'atr_period': 14, 'sl_atr': 1.6607, 'tp_atr': 3.2246, 'cooldown': 2, 'session_start': 12, 'session_end': 17, 'range_period': 31, 'range_pct': 0.3644}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["hi_range"] = df["High"].rolling(window=p["range_period"]).max()
    df["lo_range"] = df["Low"].rolling(window=p["range_period"]).min()
    df["rng_width"] = df["hi_range"] - df["lo_range"]
    df["near_low"] = df["Close"] < df["lo_range"] + p["range_pct"] * df["rng_width"]
    df["near_high"] = df["Close"] > df["hi_range"] - p["range_pct"] * df["rng_width"]
    df["signal"] = 0
    long_cond = uptrend & df["near_low"] & (df["Close"] > df["Open"]) & (df["Close"] > df["Close"].shift(1))
    short_cond = downtrend & df["near_high"] & (df["Close"] < df["Open"]) & (df["Close"] < df["Close"].shift(1))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
