"""
Strategy T00785: multi_tf_ema
Family: multi_tf_ema
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 13, 'ema_slow': 38, 'atr_period': 15, 'sl_atr': 1.5334, 'tp_atr': 3.8441, 'h1_ema': 16, 'm5_ema': 16}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["h1_ema"] = ta.trend.ema_indicator(df["Close"], window=12 * p["h1_ema"])
    df["m5_ema"] = ta.trend.ema_indicator(df["Close"], window=p["m5_ema"])
    df["signal"] = 0
    long_cond = (df["Close"] > df["h1_ema"]) & (df["m5_ema"] > df["h1_ema"]) & (df["Low"] <= df["m5_ema"]) & (df["Close"] > df["m5_ema"])
    short_cond = (df["Close"] < df["h1_ema"]) & (df["m5_ema"] < df["h1_ema"]) & (df["High"] >= df["m5_ema"]) & (df["Close"] < df["m5_ema"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
