"""
Strategy T11902: mfi_reversion
Family: mfi_reversion
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 15, 'ema_slow': 40, 'atr_period': 18, 'sl_atr': 2.29, 'tp_atr': 2.837, 'cooldown': 6, 'session_start': 9, 'session_end': 15, 'mfi_period': 13, 'mfi_low': 22, 'mfi_high': 72}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["mfi"] = ta.volume.money_flow_index(df["High"], df["Low"], df["Close"], df["Volume"], window=p["mfi_period"])
    df["signal"] = 0
    long_cond = uptrend & (df["mfi"] > p["mfi_low"]) & (df["mfi"].shift(1) <= p["mfi_low"])
    short_cond = downtrend & (df["mfi"] < p["mfi_high"]) & (df["mfi"].shift(1) >= p["mfi_high"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
