"""
Strategy T00625: rsi_bb_combo
Family: rsi_bb_combo
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 13, 'ema_slow': 79, 'atr_period': 13, 'sl_atr': 2.1953, 'tp_atr': 4.2933, 'rsi_period': 14, 'rsi_low': 21, 'rsi_high': 79, 'bb_period': 28, 'bb_std': 2.1351}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])
    df["bb_l"] = ta.volatility.bollinger_lband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])
    df["bb_h"] = ta.volatility.bollinger_hband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])
    df["signal"] = 0
    long_cond = uptrend & (df["Close"] <= df["bb_l"]) & (df["rsi"] < p["rsi_low"])
    short_cond = downtrend & (df["Close"] >= df["bb_h"]) & (df["rsi"] > p["rsi_high"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
