"""
Strategy T00041: or_logic_rsi_atr
Family: or_logic_rsi_atr
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 8, 'ema_slow': 79, 'atr_period': 13, 'sl_atr': 2.2322, 'tp_atr': 3.8288, 'rsi_period': 17, 'rsi_low': 34, 'rsi_high': 65, 'atr_ratio': 1.0055}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])
    df["atr_ma"] = df["ATR"].rolling(window=20).mean()
    df["atr_exp"] = df["ATR"] > p["atr_ratio"] * df["atr_ma"]
    df["signal"] = 0
    long_cond = uptrend & ((df["rsi"] < p["rsi_low"]) | (df["atr_exp"] & (df["Close"] > df["Open"])))
    short_cond = downtrend & ((df["rsi"] > p["rsi_high"]) | (df["atr_exp"] & (df["Close"] < df["Open"])))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
