"""
Strategy T05380: pivot_points
Family: pivot_points
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 15, 'ema_slow': 45, 'atr_period': 14, 'sl_atr': 1.6701, 'tp_atr': 3.1406, 'cooldown': 4, 'pivot_period': 124}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["pivot_h"] = df["High"].rolling(window=p["pivot_period"]).max().shift(1)
    df["pivot_l"] = df["Low"].rolling(window=p["pivot_period"]).min().shift(1)
    df["pivot_c"] = df["Close"].rolling(window=p["pivot_period"]).mean().shift(1)
    df["pp"] = (df["pivot_h"] + df["pivot_l"] + df["pivot_c"]) / 3
    df["r1"] = 2 * df["pp"] - df["pivot_l"]
    df["s1"] = 2 * df["pp"] - df["pivot_h"]
    df["signal"] = 0
    long_cond = uptrend & (df["Close"] > df["pp"]) & (df["Close"].shift(1) <= df["pp"].shift(1)) & (df["Close"] > df["Open"])
    short_cond = downtrend & (df["Close"] < df["pp"]) & (df["Close"].shift(1) >= df["pp"].shift(1)) & (df["Close"] < df["Open"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
