"""
Strategy T04275: hybrid_supertrend_rsi
Family: hybrid_supertrend_rsi
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 5, 'ema_slow': 78, 'atr_period': 20, 'sl_atr': 1.96, 'tp_atr': 2.1031, 'cooldown': 12, 'st_mult': 1.9772, 'st_period': 10, 'rsi_period': 20, 'rsi_low': 36, 'rsi_high': 64}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["st_atr"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p["st_period"])
    df["hl2"] = (df["High"] + df["Low"]) / 2
    df["st_upper"] = df["hl2"] + p["st_mult"] * df["st_atr"]
    df["st_lower"] = df["hl2"] - p["st_mult"] * df["st_atr"]
    df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])
    df["signal"] = 0
    long_cond = uptrend & (((df["Close"] > df["st_upper"]) & (df["Close"].shift(1) <= df["st_upper"].shift(1))) | ((df["rsi"] < p["rsi_low"]) & (df["rsi"].shift(1) >= p["rsi_low"])))
    short_cond = downtrend & (((df["Close"] < df["st_lower"]) & (df["Close"].shift(1) >= df["st_lower"].shift(1))) | ((df["rsi"] > p["rsi_high"]) & (df["rsi"].shift(1) <= p["rsi_high"])))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
