"""
Strategy T07796: hybrid_ichimoku_rsi
Family: hybrid_ichimoku_rsi
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 11, 'ema_slow': 36, 'atr_period': 10, 'sl_atr': 1.9736, 'tp_atr': 3.3835, 'cooldown': 4, 'session_start': 12, 'session_end': 18, 'ichi_conv': 12, 'ichi_base': 24, 'ichi_span': 48, 'rsi_period': 20, 'rsi_low': 27, 'rsi_high': 68}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    ichi = ta.trend.IchimokuIndicator(df["High"], df["Low"], window1=p["ichi_conv"], window2=p["ichi_base"], window3=p["ichi_span"])
    df["ichi_a"] = ichi.ichimoku_a()
    df["ichi_b"] = ichi.ichimoku_b()
    df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])
    df["signal"] = 0
    long_cond = uptrend & (df["Close"] > df["ichi_a"]) & (df["Close"] > df["ichi_b"]) & (df["rsi"] < p["rsi_low"]) & (df["rsi"].shift(1) >= p["rsi_low"])
    short_cond = downtrend & (df["Close"] < df["ichi_a"]) & (df["Close"] < df["ichi_b"]) & (df["rsi"] > p["rsi_high"]) & (df["rsi"].shift(1) <= p["rsi_high"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
