"""
Strategy T04247: multi_tf_rsi
Family: multi_tf_rsi
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 5, 'ema_slow': 68, 'atr_period': 19, 'sl_atr': 2.2139, 'tp_atr': 2.1885, 'cooldown': 11, 'rsi_m5': 9, 'rsi_h1_mult': 11}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["rsi_fast"] = ta.momentum.rsi(df["Close"], window=p["rsi_m5"])
    df["rsi_slow"] = ta.momentum.rsi(df["Close"], window=12 * p["rsi_h1_mult"])
    df["signal"] = 0
    long_cond = uptrend & (df["rsi_slow"] > 50) & (df["rsi_fast"] < 30) & (df["rsi_fast"].shift(1) >= 30)
    short_cond = downtrend & (df["rsi_slow"] < 50) & (df["rsi_fast"] > 70) & (df["rsi_fast"].shift(1) <= 70)
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
