"""
Strategy T00994: momentum_roc
Family: momentum_roc
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 13, 'ema_slow': 81, 'atr_period': 13, 'sl_atr': 1.9626, 'tp_atr': 2.065, 'cooldown': 6, 'roc_period': 14, 'roc_thresh': 0.5554}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["roc"] = ta.momentum.roc(df["Close"], window=p["roc_period"])
    df["signal"] = 0
    long_cond = uptrend & (df["roc"] > p["roc_thresh"]) & (df["roc"].shift(1) <= p["roc_thresh"])
    short_cond = downtrend & (df["roc"] < -p["roc_thresh"]) & (df["roc"].shift(1) >= -p["roc_thresh"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
