"""
Strategy T00725: gap_scalping
Family: gap_scalping
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {
    "ema_fast": 9,
    "ema_slow": 49,
    "atr_period": 16,
    "sl_atr": 1.39089,
    "tp_atr": 1.7951,
    "gap_pct": 0.119739
}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["gap"] = df["Open"] - df["Close"].shift(1)
    df["gap_pct_val"] = abs(df["gap"]) / df["Close"].shift(1).clip(lower=1) * 100
    df["gap_up"] = df["gap"] > 0
    df["gap_down"] = df["gap"] < 0
    df["signal"] = 0
    long_cond = uptrend & df["gap_up"] & (df["gap_pct_val"] > p["gap_pct"]) & (df["Close"] > df["Open"])
    short_cond = downtrend & df["gap_down"] & (df["gap_pct_val"] > p["gap_pct"]) & (df["Close"] < df["Open"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
