"""
Strategy T00662: hybrid_ichimoku_rsi
Family: hybrid_ichimoku_rsi
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 5, 'ema_slow': 50, 'atr_period': 13, 'sl_atr': 1.2594, 'tp_atr': 4.483, 'ichi_conv': 11, 'ichi_base': 27, 'ichi_span': 49, 'rsi_period': 16, 'rsi_low': 34, 'rsi_high': 65}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    ichi = ta.trend.IchimokuIndicator(df["High"], df["Low"], window1=p["ichi_conv"], window2=p["ichi_base"], window3=p["ichi_span"])
    df["ichi_a"] = ichi.ichimoku_a()
    df["ichi_b"] = ichi.ichimoku_b()
    df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])
    df["signal"] = 0
    long_cond = (df["Close"] > df["ichi_a"]) & (df["Close"] > df["ichi_b"]) & (df["rsi"] < p["rsi_low"])
    short_cond = (df["Close"] < df["ichi_a"]) & (df["Close"] < df["ichi_b"]) & (df["rsi"] > p["rsi_high"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
