"""
Strategy T09803: williams_percent_r
Family: williams_percent_r
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 10, 'ema_slow': 66, 'atr_period': 13, 'sl_atr': 2.0614, 'tp_atr': 3.8958, 'cooldown': 2, 'session_start': 7, 'session_end': 20, 'wr_period': 17, 'wr_low': -78, 'wr_high': -26}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["wr"] = ta.momentum.williams_r(df["High"], df["Low"], df["Close"], lbp=p["wr_period"])
    df["signal"] = 0
    long_cond = uptrend & (df["wr"] > p["wr_low"]) & (df["wr"].shift(1) <= p["wr_low"])
    short_cond = downtrend & (df["wr"] < p["wr_high"]) & (df["wr"].shift(1) >= p["wr_high"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
