"""
Strategy T00250: macd_line_cross
Family: macd_line_cross
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 10, 'ema_slow': 38, 'atr_period': 17, 'sl_atr': 2.3359, 'tp_atr': 2.6909, 'macd_fast': 14, 'macd_slow': 25, 'macd_sign': 7}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["macd_l"] = ta.trend.macd(df["Close"], window_slow=p["macd_slow"], window_fast=p["macd_fast"])
    df["macd_sig"] = ta.trend.macd_signal(df["Close"], window_slow=p["macd_slow"], window_fast=p["macd_fast"], window_sign=p["macd_sign"])
    df["signal"] = 0
    long_cond = uptrend & (df["macd_l"] > df["macd_sig"]) & (df["macd_l"].shift(1) <= df["macd_sig"].shift(1))
    short_cond = downtrend & (df["macd_l"] < df["macd_sig"]) & (df["macd_l"].shift(1) >= df["macd_sig"].shift(1))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
