"""
Strategy T12001: dmi_cross
Family: dmi_cross
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 6, 'ema_slow': 45, 'atr_period': 13, 'sl_atr': 2.0536, 'tp_atr': 3.4053, 'cooldown': 5, 'session_start': 12, 'session_end': 20, 'dmi_period': 17, 'adx_floor': 23}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["di_pos"] = ta.trend.adx_pos(df["High"], df["Low"], df["Close"], window=p["dmi_period"])
    df["di_neg"] = ta.trend.adx_neg(df["High"], df["Low"], df["Close"], window=p["dmi_period"])
    df["adx_v"] = ta.trend.adx(df["High"], df["Low"], df["Close"], window=p["dmi_period"])
    df["signal"] = 0
    long_cond = uptrend & (df["adx_v"] > p["adx_floor"]) & (df["di_pos"] > df["di_neg"]) & (df["di_pos"].shift(1) <= df["di_neg"].shift(1))
    short_cond = downtrend & (df["adx_v"] > p["adx_floor"]) & (df["di_pos"] < df["di_neg"]) & (df["di_pos"].shift(1) >= df["di_neg"].shift(1))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
