"""
Strategy T10928: hybrid_fib_macd
Family: hybrid_fib_macd
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 13, 'ema_slow': 86, 'atr_period': 10, 'sl_atr': 2.3436, 'tp_atr': 3.3962, 'cooldown': 8, 'session_start': 11, 'session_end': 15, 'fib_lookback': 29, 'fib_level': 0.5015, 'macd_fast': 15, 'macd_slow': 22, 'macd_sign': 8}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["swing_h"] = df["High"].rolling(window=p["fib_lookback"]).max()
    df["swing_l"] = df["Low"].rolling(window=p["fib_lookback"]).min()
    df["fib_buy"] = df["swing_h"] - p["fib_level"] * (df["swing_h"] - df["swing_l"])
    df["fib_sell"] = df["swing_l"] + p["fib_level"] * (df["swing_h"] - df["swing_l"])
    df["fib_cross_up"] = (df["Close"] > df["fib_buy"]) & (df["Close"].shift(1) <= df["fib_buy"].shift(1))
    df["fib_cross_dn"] = (df["Close"] < df["fib_sell"]) & (df["Close"].shift(1) >= df["fib_sell"].shift(1))
    df["macd_h"] = ta.trend.macd_diff(df["Close"], window_slow=p["macd_slow"], window_fast=p["macd_fast"], window_sign=p["macd_sign"])
    df["signal"] = 0
    long_cond = uptrend & df["fib_cross_up"] & (df["macd_h"] > df["macd_h"].shift(1))
    short_cond = downtrend & df["fib_cross_dn"] & (df["macd_h"] < df["macd_h"].shift(1))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
