"""
Strategy T07717: rsi_bb_combo
Family: rsi_bb_combo
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 7, 'ema_slow': 94, 'atr_period': 19, 'sl_atr': 1.6787, 'tp_atr': 3.6811, 'cooldown': 2, 'session_start': 9, 'session_end': 19, 'rsi_period': 13, 'rsi_low': 35, 'rsi_high': 61, 'bb_period': 27, 'bb_std': 2.693}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])
    df["bb_l"] = ta.volatility.bollinger_lband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])
    df["bb_h"] = ta.volatility.bollinger_hband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])
    df["signal"] = 0
    long_cond = uptrend & (df["Close"] <= df["bb_l"]) & (df["Close"].shift(1) > df["bb_l"].shift(1)) & (df["rsi"] < p["rsi_low"])
    short_cond = downtrend & (df["Close"] >= df["bb_h"]) & (df["Close"].shift(1) < df["bb_h"].shift(1)) & (df["rsi"] > p["rsi_high"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
