"""
Strategy T02655: volume_spike
Family: volume_spike
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 6, 'ema_slow': 58, 'atr_period': 12, 'sl_atr': 2.3328, 'tp_atr': 3.411, 'cooldown': 7, 'vol_mult': 2.6492}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["vol_ma"] = df["Volume"].rolling(window=20).mean()
    df["vol_spike"] = df["Volume"] > p["vol_mult"] * df["vol_ma"]
    df["signal"] = 0
    long_cond = uptrend & df["vol_spike"] & (df["Close"] > df["Open"]) & (df["Close"] > df["Close"].shift(1))
    short_cond = downtrend & df["vol_spike"] & (df["Close"] < df["Open"]) & (df["Close"] < df["Close"].shift(1))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
