"""
Strategy T00217: momentum_roc
Family: momentum_roc
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 9, 'ema_slow': 43, 'atr_period': 14, 'sl_atr': 1.2332, 'tp_atr': 3.5271, 'roc_period': 5, 'roc_thresh': 0.616}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["roc"] = ta.momentum.roc(df["Close"], window=p["roc_period"])
    df["signal"] = 0
    long_cond = uptrend & (df["roc"] > p["roc_thresh"]) & (df["roc"].shift(1) <= p["roc_thresh"])
    short_cond = downtrend & (df["roc"] < -p["roc_thresh"]) & (df["roc"].shift(1) >= -p["roc_thresh"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
