"""
Strategy T02662: hybrid_triple_channel
Family: hybrid_triple_channel
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 11, 'ema_slow': 45, 'atr_period': 16, 'sl_atr': 1.994, 'tp_atr': 3.9271, 'cooldown': 6, 'kc_period': 29, 'kc_mult': 1.7728, 'bb_period': 24, 'bb_std': 2.6466, 'dc_period': 20}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["kc_mid"] = ta.trend.ema_indicator(df["Close"], window=p["kc_period"])
    df["kc_atr"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p["kc_period"])
    df["kc_h"] = df["kc_mid"] + p["kc_mult"] * df["kc_atr"]
    df["kc_l"] = df["kc_mid"] - p["kc_mult"] * df["kc_atr"]
    df["bb_h"] = ta.volatility.bollinger_hband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])
    df["bb_l"] = ta.volatility.bollinger_lband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])
    df["dc_h"] = df["High"].rolling(window=p["dc_period"]).max().shift(1)
    df["dc_l"] = df["Low"].rolling(window=p["dc_period"]).min().shift(1)
    df["signal"] = 0
    long_cond = uptrend & (df["Close"] > df["kc_h"]) & (df["Close"] > df["bb_h"]) & (df["Close"] > df["dc_h"])
    short_cond = downtrend & (df["Close"] < df["kc_l"]) & (df["Close"] < df["bb_l"]) & (df["Close"] < df["dc_l"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
