"""
Strategy T00497: rsi_pullback
Family: rsi_pullback
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 12, 'ema_slow': 94, 'atr_period': 17, 'sl_atr': 2.2346, 'tp_atr': 2.6081, 'rsi_period': 20, 'rsi_low': 36, 'rsi_high': 63}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])
    df["signal"] = 0
    long_cond = uptrend & (df["rsi"] > p["rsi_low"]) & (df["rsi"].shift(1) <= p["rsi_low"])
    short_cond = downtrend & (df["rsi"] < p["rsi_high"]) & (df["rsi"].shift(1) >= p["rsi_high"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
