"""
Strategy T00768: hybrid_vol_rsi_bb
Family: hybrid_vol_rsi_bb
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 11, 'ema_slow': 34, 'atr_period': 16, 'sl_atr': 1.4668, 'tp_atr': 4.1317, 'rsi_period': 19, 'rsi_low': 23, 'rsi_high': 67, 'bb_period': 30, 'bb_std': 1.9652, 'vol_mult': 2.5237}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])
    df["bb_l"] = ta.volatility.bollinger_lband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])
    df["bb_h"] = ta.volatility.bollinger_hband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])
    df["vol_ma"] = df["Volume"].rolling(window=20).mean()
    df["vol_spike"] = df["Volume"] > p["vol_mult"] * df["vol_ma"]
    df["signal"] = 0
    long_cond = uptrend & ((df["rsi"] < p["rsi_low"]) | (df["Close"] <= df["bb_l"]) | (df["vol_spike"] & (df["Close"] > df["Open"])))
    short_cond = downtrend & ((df["rsi"] > p["rsi_high"]) | (df["Close"] >= df["bb_h"]) | (df["vol_spike"] & (df["Close"] < df["Open"])))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
