"""
Strategy T11971: fake_breakout
Family: fake_breakout
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 14, 'ema_slow': 60, 'atr_period': 12, 'sl_atr': 1.5692, 'tp_atr': 2.0714, 'cooldown': 4, 'session_start': 10, 'session_end': 21, 'fo_lookback': 28}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["hi_prev"] = df["High"].rolling(window=p["fo_lookback"]).max().shift(1)
    df["lo_prev"] = df["Low"].rolling(window=p["fo_lookback"]).min().shift(1)
    df["swept_lo"] = (df["Low"] < df["lo_prev"]) & (df["Close"] > df["lo_prev"])
    df["swept_hi"] = (df["High"] > df["hi_prev"]) & (df["Close"] < df["hi_prev"])
    df["signal"] = 0
    long_cond = uptrend & df["swept_lo"] & (df["Close"] > df["Open"])
    short_cond = downtrend & df["swept_hi"] & (df["Close"] < df["Open"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
