"""
Strategy T00212: mean_reversion_bb
Family: mean_reversion_bb
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 11, 'ema_slow': 92, 'atr_period': 18, 'sl_atr': 2.3621, 'tp_atr': 4.3984, 'rsi_period': 19, 'rsi_low': 28, 'rsi_high': 75, 'bb_period': 19, 'bb_std': 2.3868}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])
    df["bb_l"] = ta.volatility.bollinger_lband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])
    df["bb_h"] = ta.volatility.bollinger_hband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])
    df["signal"] = 0
    long_cond = (df["Close"] < df["bb_l"]) & (df["rsi"] < p["rsi_low"]) & (df["Close"] > df["Close"].shift(1))
    short_cond = (df["Close"] > df["bb_h"]) & (df["rsi"] > p["rsi_high"]) & (df["Close"] < df["Close"].shift(1))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
