"""
Strategy T07611: keltner_breakout
Family: keltner_breakout
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 8, 'ema_slow': 43, 'atr_period': 13, 'sl_atr': 2.4473, 'tp_atr': 2.349, 'cooldown': 7, 'session_start': 9, 'session_end': 15, 'kc_period': 24, 'kc_mult': 2.1733}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["kc_mid"] = ta.trend.ema_indicator(df["Close"], window=p["kc_period"])
    df["kc_atr"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p["kc_period"])
    df["kc_h"] = df["kc_mid"] + p["kc_mult"] * df["kc_atr"]
    df["kc_l"] = df["kc_mid"] - p["kc_mult"] * df["kc_atr"]
    df["signal"] = 0
    long_cond = uptrend & (df["Close"] > df["kc_h"]) & (df["Close"].shift(1) <= df["kc_h"].shift(1))
    short_cond = downtrend & (df["Close"] < df["kc_l"]) & (df["Close"].shift(1) >= df["kc_l"].shift(1))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
