"""
Strategy T00647: macd_momentum
Family: macd_momentum
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 13, 'ema_slow': 87, 'atr_period': 12, 'sl_atr': 1.0529, 'tp_atr': 2.684, 'macd_fast': 8, 'macd_slow': 20, 'macd_sign': 8}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["macd_h"] = ta.trend.macd_diff(df["Close"], window_slow=p["macd_slow"], window_fast=p["macd_fast"], window_sign=p["macd_sign"])
    df["macd_inc"] = df["macd_h"] > df["macd_h"].shift(1)
    df["macd_inc2"] = df["macd_h"].shift(1) > df["macd_h"].shift(2)
    df["signal"] = 0
    long_cond = uptrend & df["macd_inc"] & df["macd_inc2"] & (df["macd_h"] > 0)
    short_cond = downtrend & (~df["macd_inc"]) & (~df["macd_inc2"]) & (df["macd_h"] < 0)
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
