"""
Strategy T00543: fake_breakout
Family: fake_breakout
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 11, 'ema_slow': 91, 'atr_period': 11, 'sl_atr': 2.1567, 'tp_atr': 3.5676, 'fo_lookback': 27}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["hi_prev"] = df["High"].rolling(window=p["fo_lookback"]).max().shift(1)
    df["lo_prev"] = df["Low"].rolling(window=p["fo_lookback"]).min().shift(1)
    df["swept_lo"] = (df["Low"] < df["lo_prev"]) & (df["Close"] > df["lo_prev"])
    df["swept_hi"] = (df["High"] > df["hi_prev"]) & (df["Close"] < df["hi_prev"])
    df["signal"] = 0
    long_cond = uptrend & df["swept_lo"] & (df["Close"] > df["Open"])
    short_cond = downtrend & df["swept_hi"] & (df["Close"] < df["Open"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
