"""
Strategy T08335: momentum_breakout
Family: momentum_breakout
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 7, 'ema_slow': 100, 'atr_period': 14, 'sl_atr': 1.9151, 'tp_atr': 2.0431, 'cooldown': 8, 'session_start': 11, 'session_end': 16, 'body_atr_mult': 2.1485, 'vol_mult': 1.6935}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["body"] = abs(df["Close"] - df["Open"])
    df["vol_ma"] = df["Volume"].rolling(window=20).mean()
    df["big_body"] = df["body"] > p["body_atr_mult"] * df["ATR"]
    df["big_vol"] = df["Volume"] > p["vol_mult"] * df["vol_ma"]
    df["signal"] = 0
    long_cond = uptrend & df["big_body"] & df["big_vol"] & (df["Close"] > df["Open"]) & (df["Close"] > df["High"].shift(1))
    short_cond = downtrend & df["big_body"] & df["big_vol"] & (df["Close"] < df["Open"]) & (df["Close"] < df["Low"].shift(1))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
