"""
Strategy T00749: hybrid_session_volume
Family: hybrid_session_volume
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 12, 'ema_slow': 95, 'atr_period': 10, 'sl_atr': 1.57, 'tp_atr': 3.837, 'range_bars': 9, 'vol_mult': 1.2303}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["hour"] = pd.to_datetime(df["time"]).dt.hour
    df["in_session"] = (df["hour"] >= 8) & (df["hour"] <= 16)
    df["range_hi"] = df["High"].rolling(window=p["range_bars"]).max().shift(1)
    df["range_lo"] = df["Low"].rolling(window=p["range_bars"]).min().shift(1)
    df["vol_ma"] = df["Volume"].rolling(window=20).mean()
    df["vol_ok"] = df["Volume"] > p["vol_mult"] * df["vol_ma"]
    df["signal"] = 0
    long_cond = uptrend & df["in_session"] & df["vol_ok"] & (df["Close"] > df["range_hi"])
    short_cond = downtrend & df["in_session"] & df["vol_ok"] & (df["Close"] < df["range_lo"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
