"""
Strategy T02800: hybrid_macd_bb
Family: hybrid_macd_bb
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 10, 'ema_slow': 48, 'atr_period': 16, 'sl_atr': 1.8617, 'tp_atr': 3.7713, 'cooldown': 6, 'macd_fast': 8, 'macd_slow': 29, 'macd_sign': 12, 'bb_period': 16, 'bb_std': 2.6956}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["macd_h"] = ta.trend.macd_diff(df["Close"], window_slow=p["macd_slow"], window_fast=p["macd_fast"], window_sign=p["macd_sign"])
    df["bb_h"] = ta.volatility.bollinger_hband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])
    df["bb_l"] = ta.volatility.bollinger_lband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])
    df["signal"] = 0
    long_cond = uptrend & (((df["macd_h"] > 0) & (df["macd_h"].shift(1) <= 0)) | ((df["Close"] <= df["bb_l"]) & (df["Close"].shift(1) > df["bb_l"].shift(1))))
    short_cond = downtrend & (((df["macd_h"] < 0) & (df["macd_h"].shift(1) >= 0)) | ((df["Close"] >= df["bb_h"]) & (df["Close"].shift(1) < df["bb_h"].shift(1))))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
