"""
Strategy T08416: macd_momentum
Family: macd_momentum
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 6, 'ema_slow': 52, 'atr_period': 19, 'sl_atr': 1.6385, 'tp_atr': 3.632, 'cooldown': 3, 'session_start': 12, 'session_end': 15, 'macd_fast': 15, 'macd_slow': 29, 'macd_sign': 8}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["macd_h"] = ta.trend.macd_diff(df["Close"], window_slow=p["macd_slow"], window_fast=p["macd_fast"], window_sign=p["macd_sign"])
    df["macd_inc"] = df["macd_h"] > df["macd_h"].shift(1)
    df["macd_inc2"] = df["macd_h"].shift(1) > df["macd_h"].shift(2)
    df["signal"] = 0
    long_cond = uptrend & (df["macd_h"] > 0) & (df["macd_h"].shift(1) <= 0) & df["macd_inc"]
    short_cond = downtrend & (df["macd_h"] < 0) & (df["macd_h"].shift(1) >= 0) & (~df["macd_inc"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
