"""
Strategy T07431: double_pattern
Family: double_pattern
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 9, 'ema_slow': 99, 'atr_period': 10, 'sl_atr': 2.4024, 'tp_atr': 2.2982, 'cooldown': 6, 'session_start': 10, 'session_end': 15, 'lookback': 32, 'tolerance': 0.0021}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["lo_prev"] = df["Low"].rolling(window=p["lookback"]).min()
    df["hi_prev"] = df["High"].rolling(window=p["lookback"]).max()
    df["lo_recent"] = df["Low"].rolling(window=p["lookback"]//2).min()
    df["hi_recent"] = df["High"].rolling(window=p["lookback"]//2).max()
    df["dbl_bot"] = abs(df["lo_recent"] - df["lo_prev"]) / df["Close"].clip(lower=1) < p["tolerance"]
    df["dbl_top"] = abs(df["hi_recent"] - df["hi_prev"]) / df["Close"].clip(lower=1) < p["tolerance"]
    df["signal"] = 0
    long_cond = uptrend & df["dbl_bot"] & (df["Close"] > df["Open"]) & (df["Close"] > df["Close"].shift(1))
    short_cond = downtrend & df["dbl_top"] & (df["Close"] < df["Open"]) & (df["Close"] < df["Close"].shift(1))
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
