"""
Strategy T00268: triple_ema_pullback
Family: triple_ema_pullback
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {'ema_fast': 15, 'ema_slow': 63, 'atr_period': 11, 'sl_atr': 2.4844, 'tp_atr': 2.5137, 'ema_1': 10, 'ema_2': 24, 'ema_3': 49}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["e1"] = ta.trend.ema_indicator(df["Close"], window=p["ema_1"])
    df["e2"] = ta.trend.ema_indicator(df["Close"], window=p["ema_2"])
    df["e3"] = ta.trend.ema_indicator(df["Close"], window=p["ema_3"])
    df["signal"] = 0
    long_cond = (df["e1"] > df["e2"]) & (df["e2"] > df["e3"]) & (df["Low"] <= df["e2"]) & (df["Close"] > df["e2"])
    short_cond = (df["e1"] < df["e2"]) & (df["e2"] < df["e3"]) & (df["High"] >= df["e2"]) & (df["Close"] < df["e2"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    return df
