"""
Strategy T03674: gap_scalping
Family: gap_scalping
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta

PARAMS = {
    "redundant": true,
    "atr_period": 20,
    "ema_fast": 15,
    "component_ids": [
        "c007",
        "T01736",
        "T00903"
    ],
    "tp_atr": 2.3495,
    "multi_timeframe": {
        "baseline_pf": 0.6335,
        "best_htf": null,
        "best_pf": 0.6335,
        "improvement": 1.0,
        "htf_results": {
            "M5": {
                "pf": 0.7093,
                "wr": 0.4848,
                "trades": 33,
                "improvement": 1.1197
            },
            "M15": {
                "pf": 0.7409,
                "wr": 0.5217,
                "trades": 46,
                "improvement": 1.1695
            },
            "H1": {
                "pf": 0.7878,
                "wr": 0.5385,
                "trades": 52,
                "improvement": 1.2436
            }
        }
    },
    "cooldown": 6,
    "gap_pct": 0.0642,
    "sl_atr": 1.7014,
    "weights": {
        "c007": 6.7682,
        "T01736": 2.9218,
        "T00903": 2.6287
    },
    "method": "vote",
    "ema_slow": 32,
    "monte_carlo_tested": true,
    "mtf_tested": true,
    "avg_sl_atr": 1.9373,
    "avg_tp_atr": 2.9485,
    "redundant_of": "ENS_VOTE_027",
    "monte_carlo": {
        "median_dd": 0.0722,
        "p95_dd": 0.1283,
        "p_x10": 0.0,
        "p_ruin": 0.0,
        "n_simulations": 10000
    },
    "redundant_cluster": [
        "T00903",
        "ENS_VOTE_006",
        "ENS_WEIGHTED_006",
        "ENS_VOTE_013",
        "ENS_WEIGHTED_013",
        "ENS_VOTE_019",
        "ENS_WEIGHTED_019",
        "ENS_VOTE_023",
        "ENS_WEIGHTED_023",
        "ENS_VOTE_024",
        "ENS_WEIGHTED_024",
        "ENS_VOTE_025",
        "ENS_WEIGHTED_025",
        "ENS_VOTE_026",
        "ENS_WEIGHTED_026",
        "ENS_VOTE_027",
        "ENS_WEIGHTED_027",
        "ENS_VOTE_028",
        "ENS_WEIGHTED_028",
        "ENS_VOTE_029",
        "ENS_WEIGHTED_029",
        "ENS_VOTE_030",
        "ENS_WEIGHTED_030",
        "ENS_VOTE_031",
        "ENS_WEIGHTED_031",
        "ENS_VOTE_032",
        "ENS_WEIGHTED_032",
        "ENS_VOTE_033",
        "ENS_WEIGHTED_033",
        "ENS_VOTE_034",
        "ENS_WEIGHTED_034",
        "ENS_VOTE_035",
        "ENS_WEIGHTED_035",
        "ENS_VOTE_036",
        "ENS_WEIGHTED_036",
        "ENS_VOTE_037",
        "ENS_WEIGHTED_037",
        "ENS_VOTE_038",
        "ENS_WEIGHTED_038",
        "ENS_VOTE_039",
        "ENS_WEIGHTED_039",
        "ENS_VOTE_040",
        "ENS_WEIGHTED_040",
        "ENS_VOTE_041",
        "ENS_WEIGHTED_041",
        "ENS_VOTE_042",
        "ENS_WEIGHTED_042"
    ]
}

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
    df["gap"] = df["Open"] - df["Close"].shift(1)
    df["gap_pct_val"] = abs(df["gap"]) / df["Close"].shift(1).clip(lower=1) * 100
    df["gap_up"] = df["gap"] > 0
    df["gap_down"] = df["gap"] < 0
    df["signal"] = 0
    long_cond = uptrend & df["gap_up"] & (df["gap_pct_val"] > p["gap_pct"]) & (df["Close"] > df["Open"])
    short_cond = downtrend & df["gap_down"] & (df["gap_pct_val"] > p["gap_pct"]) & (df["Close"] < df["Open"])
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
