"""
Template Factory Agent: mass-generates strategies from parametric templates
without needing an LLM.  Each strategy is a Python file that defines a PARAMS
dict and a generate_signals(df, p) function.

All strategies target M5 timeframe with EMA-stack trend filter.
"""
import ast
import json
import random
import re
from pathlib import Path

from agents.base_agent import BaseAgent
from agents.strategy_factory import validate_strategy_code
from core.config import STRATEGIES_DIR

# ---------------------------------------------------------------------------
# Strategy code template
# ---------------------------------------------------------------------------
STRATEGY_TEMPLATE = '''\
"""
Strategy __ID__: __FAMILY__
Family: __FAMILY__
Timeframe: M5
Auto-generated by TemplateFactory
"""
import pandas as pd
import numpy as np
import ta


def _combine_triggers(triggers, mode):
    """Combine the trigger conditions per the searchable 'logic' gene.
    'and' = all (strict, rare) · 'or' = any (loose, frequent) ·
    '2of3' = majority (balanced). The trend filter stays mandatory outside."""
    if not triggers:
        return None
    if mode == "or":
        out = triggers[0]
        for t in triggers[1:]:
            out = out | t
        return out
    if mode == "majority" and len(triggers) >= 2:
        s = sum(t.astype("boolean").fillna(False).astype(int) for t in triggers)
        return s >= max(1, (len(triggers) + 1) // 2)
    out = triggers[0]
    for t in triggers[1:]:
        out = out & t
    return out


PARAMS = __PARAMS__

def generate_signals(df: pd.DataFrame, p: dict = PARAMS) -> pd.DataFrame:
    df["ATR"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p.get("atr_period", 14))
    df["ema_f"] = ta.trend.ema_indicator(df["Close"], window=p["ema_fast"])
    df["ema_s"] = ta.trend.ema_indicator(df["Close"], window=p["ema_slow"])
    uptrend = df["ema_f"] > df["ema_s"]
    downtrend = df["ema_f"] < df["ema_s"]
__INDICATORS__
    df["signal"] = 0
    _logic = p.get("logic", "and")
    _long_trig = _combine_triggers([__LONG_TRIG__], _logic)
    _short_trig = _combine_triggers([__SHORT_TRIG__], _logic)
    long_cond = (__LONG_TREND__) & _long_trig if _long_trig is not None else (__LONG_TREND__)
    short_cond = (__SHORT_TREND__) & _short_trig if _short_trig is not None else (__SHORT_TREND__)
    df.loc[long_cond, "signal"] = 1
    df.loc[short_cond, "signal"] = -1
    # Cooldown: suppress signals within N bars of last signal
    cooldown = p.get("cooldown", 6)
    if cooldown > 0:
        sigs = df["signal"].values.copy()
        last_sig = -cooldown - 1
        for i in range(len(sigs)):
            if sigs[i] != 0:
                if i - last_sig <= cooldown:
                    sigs[i] = 0
                else:
                    last_sig = i
        df["signal"] = sigs
    return df
'''

# ---------------------------------------------------------------------------
# Base parameter ranges shared by every template
# ---------------------------------------------------------------------------
BASE_PARAMS = {
    "ema_fast": (5, 15),
    "ema_slow": (30, 100),
    "atr_period": (10, 20),
    "sl_atr": (1.5, 2.5),       # analyzer: <1.5 always blows (spread drag)
    "tp_atr": (2.0, 4.0),       # analyzer: optimal range [2.0, 4.0]
    "cooldown": (2, 8),          # bars between signals — tighter to boost signal frequency
    # Trading session (server hours) — a search dimension of its own: the
    # same signal logic can be gold in the London/NY overlap and noise in
    # the Asian session. Ranges guarantee start < end.
    "session_start": (7, 12),
    "session_end": (15, 21),
    # Trailing stop as a searchable gene (0=fixed SL/TP, 1=trail after 1R).
    # The engine hard-disables it when tp_atr >= 3.0 (proven to kill
    # wide-TP strategies) regardless of this value.
    "trailing": (0, 1),
}

# ---------------------------------------------------------------------------
# 20 diverse template definitions
# ---------------------------------------------------------------------------
TEMPLATES = [
    # 1 ---------------------------------------------------------------
    {
        "family": "rsi_pullback",
        "extra_params": {
            "rsi_period": (7, 21),
            "rsi_low": (20, 40),
            "rsi_high": (60, 80),
        },
        "indicators": [
            'df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])',
        ],
        "long": 'uptrend & (df["rsi"] > p["rsi_low"]) & (df["rsi"].shift(1) <= p["rsi_low"])',
        "short": 'downtrend & (df["rsi"] < p["rsi_high"]) & (df["rsi"].shift(1) >= p["rsi_high"])',
    },
    # 2 ---------------------------------------------------------------
    {
        "family": "bollinger_breakout",
        "extra_params": {
            "bb_period": (15, 30),
            "bb_std": (1.5, 3.0),
        },
        "indicators": [
            'df["bb_h"] = ta.volatility.bollinger_hband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])',
            'df["bb_l"] = ta.volatility.bollinger_lband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])',
        ],
        "long": 'uptrend & (df["Close"] > df["bb_h"]) & (df["Close"].shift(1) <= df["bb_h"].shift(1))',
        "short": 'downtrend & (df["Close"] < df["bb_l"]) & (df["Close"].shift(1) >= df["bb_l"].shift(1))',
    },
    # 3 ---------------------------------------------------------------
    {
        "family": "macd_histogram",
        "extra_params": {
            "macd_fast": (8, 15),
            "macd_slow": (20, 30),
            "macd_sign": (7, 12),
        },
        "indicators": [
            'df["macd_h"] = ta.trend.macd_diff(df["Close"], window_slow=p["macd_slow"], window_fast=p["macd_fast"], window_sign=p["macd_sign"])',
        ],
        "long": 'uptrend & (df["macd_h"] > 0) & (df["macd_h"].shift(1) <= 0)',
        "short": 'downtrend & (df["macd_h"] < 0) & (df["macd_h"].shift(1) >= 0)',
    },
    # 4 ---------------------------------------------------------------
    {
        "family": "adx_breakout",
        "extra_params": {
            "adx_period": (10, 25),
            "adx_thresh": (20, 35),
        },
        "indicators": [
            'df["adx_val"] = ta.trend.adx(df["High"], df["Low"], df["Close"], window=p["adx_period"])',
            'df["di_p"] = ta.trend.adx_pos(df["High"], df["Low"], df["Close"], window=p["adx_period"])',
            'df["di_n"] = ta.trend.adx_neg(df["High"], df["Low"], df["Close"], window=p["adx_period"])',
        ],
        "long": '(df["adx_val"] > p["adx_thresh"]) & (df["di_p"] > df["di_n"]) & (df["di_p"].shift(1) <= df["di_n"].shift(1))',
        "short": '(df["adx_val"] > p["adx_thresh"]) & (df["di_n"] > df["di_p"]) & (df["di_n"].shift(1) <= df["di_p"].shift(1))',
    },
    # 5 ---------------------------------------------------------------
    {
        "family": "rsi_macd_dual",
        "extra_params": {
            "rsi_period": (7, 21),
            "rsi_low": (20, 40),
            "rsi_high": (60, 80),
            "macd_fast": (8, 15),
            "macd_slow": (20, 30),
            "macd_sign": (7, 12),
        },
        "indicators": [
            'df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])',
            'df["macd_h"] = ta.trend.macd_diff(df["Close"], window_slow=p["macd_slow"], window_fast=p["macd_fast"], window_sign=p["macd_sign"])',
        ],
        "long": 'uptrend & (df["rsi"] < p["rsi_low"]) & (df["rsi"].shift(1) >= p["rsi_low"]) & (df["macd_h"] > df["macd_h"].shift(1))',
        "short": 'downtrend & (df["rsi"] > p["rsi_high"]) & (df["rsi"].shift(1) <= p["rsi_high"]) & (df["macd_h"] < df["macd_h"].shift(1))',
    },
    # 6 ---------------------------------------------------------------
    {
        "family": "ema_bounce",
        "extra_params": {
            "ema_mid": (15, 30),
        },
        "indicators": [
            'df["ema_m"] = ta.trend.ema_indicator(df["Close"], window=p["ema_mid"])',
        ],
        "long": 'uptrend & (df["Low"] <= df["ema_m"]) & (df["Close"] > df["ema_m"]) & (df["Close"] > df["Open"])',
        "short": 'downtrend & (df["High"] >= df["ema_m"]) & (df["Close"] < df["ema_m"]) & (df["Close"] < df["Open"])',
    },
    # 7 ---------------------------------------------------------------
    {
        "family": "atr_expansion",
        "extra_params": {
            "atr_mult": (1.5, 3.0),
        },
        "indicators": [
            'df["atr_ma"] = df["ATR"].rolling(window=20).mean()',
            'df["body"] = abs(df["Close"] - df["Open"])',
        ],
        "long": 'uptrend & (df["body"] > p["atr_mult"] * df["atr_ma"]) & (df["Close"] > df["Open"])',
        "short": 'downtrend & (df["body"] > p["atr_mult"] * df["atr_ma"]) & (df["Close"] < df["Open"])',
    },
    # 8 ---------------------------------------------------------------
    {
        "family": "rsi_bb_combo",
        "extra_params": {
            "rsi_period": (7, 21),
            "rsi_low": (20, 40),
            "rsi_high": (60, 80),
            "bb_period": (15, 30),
            "bb_std": (1.5, 3.0),
        },
        "indicators": [
            'df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])',
            'df["bb_l"] = ta.volatility.bollinger_lband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])',
            'df["bb_h"] = ta.volatility.bollinger_hband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])',
        ],
        "long": 'uptrend & (df["Close"] <= df["bb_l"]) & (df["Close"].shift(1) > df["bb_l"].shift(1)) & (df["rsi"] < p["rsi_low"])',
        "short": 'downtrend & (df["Close"] >= df["bb_h"]) & (df["Close"].shift(1) < df["bb_h"].shift(1)) & (df["rsi"] > p["rsi_high"])',
    },
    # 9 ---------------------------------------------------------------
    {
        "family": "triple_ema_pullback",
        "extra_params": {
            "ema_1": (5, 10),
            "ema_2": (15, 25),
            "ema_3": (40, 60),
        },
        "indicators": [
            'df["e1"] = ta.trend.ema_indicator(df["Close"], window=p["ema_1"])',
            'df["e2"] = ta.trend.ema_indicator(df["Close"], window=p["ema_2"])',
            'df["e3"] = ta.trend.ema_indicator(df["Close"], window=p["ema_3"])',
        ],
        "long": '(df["e1"] > df["e2"]) & (df["e2"] > df["e3"]) & (df["Low"] <= df["e2"]) & (df["Close"] > df["e2"])',
        "short": '(df["e1"] < df["e2"]) & (df["e2"] < df["e3"]) & (df["High"] >= df["e2"]) & (df["Close"] < df["e2"])',
    },
    # 10 --------------------------------------------------------------
    {
        "family": "momentum_roc",
        "extra_params": {
            "roc_period": (5, 15),
            "roc_thresh": (0.3, 1.0),
        },
        "indicators": [
            'df["roc"] = ta.momentum.roc(df["Close"], window=p["roc_period"])',
        ],
        "long": 'uptrend & (df["roc"] > p["roc_thresh"]) & (df["roc"].shift(1) <= p["roc_thresh"])',
        "short": 'downtrend & (df["roc"] < -p["roc_thresh"]) & (df["roc"].shift(1) >= -p["roc_thresh"])',
    },
    # 11 --------------------------------------------------------------
    {
        "family": "macd_line_cross",
        "extra_params": {
            "macd_fast": (8, 15),
            "macd_slow": (20, 30),
            "macd_sign": (7, 12),
        },
        "indicators": [
            'df["macd_l"] = ta.trend.macd(df["Close"], window_slow=p["macd_slow"], window_fast=p["macd_fast"])',
            'df["macd_sig"] = ta.trend.macd_signal(df["Close"], window_slow=p["macd_slow"], window_fast=p["macd_fast"], window_sign=p["macd_sign"])',
        ],
        "long": 'uptrend & (df["macd_l"] > df["macd_sig"]) & (df["macd_l"].shift(1) <= df["macd_sig"].shift(1))',
        "short": 'downtrend & (df["macd_l"] < df["macd_sig"]) & (df["macd_l"].shift(1) >= df["macd_sig"].shift(1))',
    },
    # 12 --------------------------------------------------------------
    {
        "family": "bb_squeeze",
        "extra_params": {
            "bb_period": (15, 30),
            "bb_std": (1.5, 3.0),
            "sq_pct": (0.3, 0.7),
        },
        "indicators": [
            'df["bb_w"] = ta.volatility.bollinger_wband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])',
            'df["bb_w_ma"] = df["bb_w"].rolling(window=50).mean()',
            'df["squeeze"] = df["bb_w"] < p["sq_pct"] * df["bb_w_ma"]',
            'df["was_sq"] = df["squeeze"].shift(1).fillna(False)',
            'df["bb_h"] = ta.volatility.bollinger_hband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])',
            'df["bb_l"] = ta.volatility.bollinger_lband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])',
        ],
        "long": 'uptrend & df["was_sq"] & ~df["squeeze"] & (df["Close"] > df["bb_h"])',
        "short": 'downtrend & df["was_sq"] & ~df["squeeze"] & (df["Close"] < df["bb_l"])',
    },
    # 13 --------------------------------------------------------------
    {
        "family": "breakout_nbar",
        "extra_params": {
            "lookback": (10, 30),
        },
        "indicators": [
            'df["hi_n"] = df["High"].rolling(window=p["lookback"]).max().shift(1)',
            'df["lo_n"] = df["Low"].rolling(window=p["lookback"]).min().shift(1)',
        ],
        "long": 'uptrend & (df["Close"] > df["hi_n"]) & (df["Close"].shift(1) <= df["hi_n"].shift(1))',
        "short": 'downtrend & (df["Close"] < df["lo_n"]) & (df["Close"].shift(1) >= df["lo_n"].shift(1))',
    },
    # 14 --------------------------------------------------------------
    {
        "family": "or_logic_rsi_atr",
        "extra_params": {
            "rsi_period": (7, 21),
            "rsi_low": (20, 40),
            "rsi_high": (60, 80),
            "atr_ratio": (1.0, 2.0),
        },
        "indicators": [
            'df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])',
            'df["atr_ma"] = df["ATR"].rolling(window=20).mean()',
            'df["atr_exp"] = df["ATR"] > p["atr_ratio"] * df["atr_ma"]',
        ],
        "long": 'uptrend & (((df["rsi"] < p["rsi_low"]) & (df["rsi"].shift(1) >= p["rsi_low"])) | (df["atr_exp"] & (~df["atr_exp"].shift(1).fillna(False)) & (df["Close"] > df["Open"])))',
        "short": 'downtrend & (((df["rsi"] > p["rsi_high"]) & (df["rsi"].shift(1) <= p["rsi_high"])) | (df["atr_exp"] & (~df["atr_exp"].shift(1).fillna(False)) & (df["Close"] < df["Open"])))',
    },
    # 15 --------------------------------------------------------------
    {
        "family": "dual_rsi",
        "extra_params": {
            "rsi_fast": (5, 10),
            "rsi_slow": (14, 25),
        },
        "indicators": [
            'df["rsi_f"] = ta.momentum.rsi(df["Close"], window=p["rsi_fast"])',
            'df["rsi_s"] = ta.momentum.rsi(df["Close"], window=p["rsi_slow"])',
        ],
        "long": 'uptrend & (df["rsi_f"] > df["rsi_s"]) & (df["rsi_f"].shift(1) <= df["rsi_s"].shift(1)) & (df["rsi_s"] < 50)',
        "short": 'downtrend & (df["rsi_f"] < df["rsi_s"]) & (df["rsi_f"].shift(1) >= df["rsi_s"].shift(1)) & (df["rsi_s"] > 50)',
    },
    # 16 --------------------------------------------------------------
    {
        "family": "engulfing_candle",
        "extra_params": {
            "body_ratio": (1.5, 3.0),
            "atr_mult": (1.0, 1.5),
        },
        "indicators": [
            'df["body"] = abs(df["Close"] - df["Open"])',
            'df["prev_body"] = df["body"].shift(1)',
            'df["bull"] = df["Close"] > df["Open"]',
            'df["atr_ma"] = df["ATR"].rolling(window=20).mean()',
        ],
        "long": 'uptrend & df["bull"] & (~df["bull"].shift(1).fillna(True)) & (df["body"] > p["body_ratio"] * df["prev_body"]) & (df["ATR"] > p["atr_mult"] * df["atr_ma"])',
        "short": 'downtrend & (~df["bull"]) & df["bull"].shift(1).fillna(False) & (df["body"] > p["body_ratio"] * df["prev_body"]) & (df["ATR"] > p["atr_mult"] * df["atr_ma"])',
    },
    # 17 --------------------------------------------------------------
    {
        "family": "keltner_breakout",
        "extra_params": {
            "kc_period": (15, 30),
            "kc_mult": (1.5, 3.0),
        },
        "indicators": [
            'df["kc_mid"] = ta.trend.ema_indicator(df["Close"], window=p["kc_period"])',
            'df["kc_atr"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p["kc_period"])',
            'df["kc_h"] = df["kc_mid"] + p["kc_mult"] * df["kc_atr"]',
            'df["kc_l"] = df["kc_mid"] - p["kc_mult"] * df["kc_atr"]',
        ],
        "long": 'uptrend & (df["Close"] > df["kc_h"]) & (df["Close"].shift(1) <= df["kc_h"].shift(1))',
        "short": 'downtrend & (df["Close"] < df["kc_l"]) & (df["Close"].shift(1) >= df["kc_l"].shift(1))',
    },
    # 18 --------------------------------------------------------------
    {
        "family": "rsi_pin_bar",
        "extra_params": {
            "rsi_period": (7, 21),
            "rsi_low": (20, 40),
            "rsi_high": (60, 80),
            "wick_ratio": (1.5, 3.0),
        },
        "indicators": [
            'df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])',
            'df["body"] = abs(df["Close"] - df["Open"]).clip(lower=0.01)',
            'df["lo_wick"] = df[["Close", "Open"]].min(axis=1) - df["Low"]',
            'df["hi_wick"] = df["High"] - df[["Close", "Open"]].max(axis=1)',
        ],
        "long": 'uptrend & (df["rsi"] < p["rsi_low"]) & (df["lo_wick"] > p["wick_ratio"] * df["body"]) & (df["Close"] > df["Open"])',
        "short": 'downtrend & (df["rsi"] > p["rsi_high"]) & (df["hi_wick"] > p["wick_ratio"] * df["body"]) & (df["Close"] < df["Open"])',
    },
    # 19 --------------------------------------------------------------
    {
        "family": "macd_momentum",
        "extra_params": {
            "macd_fast": (8, 15),
            "macd_slow": (20, 30),
            "macd_sign": (7, 12),
        },
        "indicators": [
            'df["macd_h"] = ta.trend.macd_diff(df["Close"], window_slow=p["macd_slow"], window_fast=p["macd_fast"], window_sign=p["macd_sign"])',
            'df["macd_inc"] = df["macd_h"] > df["macd_h"].shift(1)',
            'df["macd_inc2"] = df["macd_h"].shift(1) > df["macd_h"].shift(2)',
        ],
        "long": 'uptrend & (df["macd_h"] > 0) & (df["macd_h"].shift(1) <= 0) & df["macd_inc"]',
        "short": 'downtrend & (df["macd_h"] < 0) & (df["macd_h"].shift(1) >= 0) & (~df["macd_inc"])',
    },
    # 20 --------------------------------------------------------------
    {
        "family": "mean_reversion_bb",
        "extra_params": {
            "rsi_period": (7, 21),
            "rsi_low": (20, 35),
            "rsi_high": (65, 80),
            "bb_period": (15, 30),
            "bb_std": (1.5, 3.0),
        },
        "indicators": [
            'df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])',
            'df["bb_l"] = ta.volatility.bollinger_lband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])',
            'df["bb_h"] = ta.volatility.bollinger_hband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])',
        ],
        "long": 'uptrend & (df["Close"] < df["bb_l"]) & (df["rsi"] < p["rsi_low"]) & (df["Close"] > df["Close"].shift(1))',
        "short": 'downtrend & (df["Close"] > df["bb_h"]) & (df["rsi"] > p["rsi_high"]) & (df["Close"] < df["Close"].shift(1))',
    },
    # 21 — Stochastic crossover ────────────────────────────────────────
    {
        "family": "stochastic_cross",
        "extra_params": {
            "stoch_k": (5, 21), "stoch_d": (3, 7),
            "stoch_low": (15, 30), "stoch_high": (70, 85),
        },
        "indicators": [
            'df["sk"] = ta.momentum.stoch(df["High"], df["Low"], df["Close"], window=p["stoch_k"], smooth_window=p["stoch_d"])',
            'df["sd"] = ta.momentum.stoch_signal(df["High"], df["Low"], df["Close"], window=p["stoch_k"], smooth_window=p["stoch_d"])',
        ],
        "long": 'uptrend & (df["sk"] > df["sd"]) & (df["sk"].shift(1) <= df["sd"].shift(1)) & (df["sk"].shift(1) < p["stoch_low"])',
        "short": 'downtrend & (df["sk"] < df["sd"]) & (df["sk"].shift(1) >= df["sd"].shift(1)) & (df["sk"].shift(1) > p["stoch_high"])',
    },
    # 22 — Ichimoku cloud ──────────────────────────────────────────────
    {
        "family": "ichimoku_cloud",
        "extra_params": {
            "ichi_conv": (7, 12), "ichi_base": (20, 30), "ichi_span": (40, 60),
        },
        "indicators": [
            'ichi = ta.trend.IchimokuIndicator(df["High"], df["Low"], window1=p["ichi_conv"], window2=p["ichi_base"], window3=p["ichi_span"])',
            'df["ichi_a"] = ichi.ichimoku_a()',
            'df["ichi_b"] = ichi.ichimoku_b()',
            'df["ichi_conv"] = ichi.ichimoku_conversion_line()',
            'df["ichi_base"] = ichi.ichimoku_base_line()',
            'df["above_cloud"] = (df["Close"] > df["ichi_a"]) & (df["Close"] > df["ichi_b"])',
            'df["below_cloud"] = (df["Close"] < df["ichi_a"]) & (df["Close"] < df["ichi_b"])',
        ],
        "long": 'uptrend & df["above_cloud"] & (df["ichi_conv"] > df["ichi_base"]) & (df["ichi_conv"].shift(1) <= df["ichi_base"].shift(1))',
        "short": 'downtrend & df["below_cloud"] & (df["ichi_conv"] < df["ichi_base"]) & (df["ichi_conv"].shift(1) >= df["ichi_base"].shift(1))',
    },
    # 23 — Supertrend ──────────────────────────────────────────────────
    {
        "family": "supertrend",
        "extra_params": {
            "st_mult": (1.5, 3.0), "st_period": (7, 15),
        },
        "indicators": [
            'df["st_atr"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p["st_period"])',
            'df["hl2"] = (df["High"] + df["Low"]) / 2',
            'df["st_upper"] = df["hl2"] + p["st_mult"] * df["st_atr"]',
            'df["st_lower"] = df["hl2"] - p["st_mult"] * df["st_atr"]',
        ],
        "long": 'uptrend & (df["Close"] > df["st_upper"]) & (df["Close"].shift(1) <= df["st_upper"].shift(1))',
        "short": 'downtrend & (df["Close"] < df["st_lower"]) & (df["Close"].shift(1) >= df["st_lower"].shift(1))',
    },
    # 24 — Parabolic SAR ──────────────────────────────────────────────
    {
        "family": "parabolic_sar",
        "extra_params": {
            "atr_mult": (1.0, 1.5),
        },
        "indicators": [
            'psar_ind = ta.trend.PSARIndicator(df["High"], df["Low"], df["Close"])',
            'df["psar_up"] = psar_ind.psar_up()',
            'df["psar_down"] = psar_ind.psar_down()',
            'df["atr_ma"] = df["ATR"].rolling(window=20).mean()',
        ],
        "long": 'uptrend & df["psar_up"].notna() & df["psar_up"].shift(1).isna() & (df["ATR"] > p["atr_mult"] * df["atr_ma"])',
        "short": 'downtrend & df["psar_down"].notna() & df["psar_down"].shift(1).isna() & (df["ATR"] > p["atr_mult"] * df["atr_ma"])',
    },
    # 25 — Donchian Channel pullback ──────────────────────────────────
    {
        "family": "donchian_pullback",
        "extra_params": {"dc_period": (10, 30)},
        "indicators": [
            'df["dc_h"] = df["High"].rolling(window=p["dc_period"]).max().shift(1)',
            'df["dc_l"] = df["Low"].rolling(window=p["dc_period"]).min().shift(1)',
            'df["dc_mid"] = (df["dc_h"] + df["dc_l"]) / 2',
        ],
        "long": 'uptrend & (df["Low"] <= df["dc_mid"]) & (df["Close"] > df["dc_mid"]) & (df["Close"] > df["Open"])',
        "short": 'downtrend & (df["High"] >= df["dc_mid"]) & (df["Close"] < df["dc_mid"]) & (df["Close"] < df["Open"])',
    },
    # 26 — Volume spike ────────────────────────────────────────────────
    {
        "family": "volume_spike",
        "extra_params": {"vol_mult": (1.5, 3.0)},
        "indicators": [
            'df["vol_ma"] = df["Volume"].rolling(window=20).mean()',
            'df["vol_spike"] = df["Volume"] > p["vol_mult"] * df["vol_ma"]',
        ],
        "long": 'uptrend & df["vol_spike"] & (df["Close"] > df["Open"]) & (df["Close"] > df["Close"].shift(1))',
        "short": 'downtrend & df["vol_spike"] & (df["Close"] < df["Open"]) & (df["Close"] < df["Close"].shift(1))',
    },
    # 27 — Fibonacci retracement ──────────────────────────────────────
    {
        "family": "fibonacci_retrace",
        "extra_params": {"fib_lookback": (20, 60), "fib_level": (0.3, 0.7)},
        "indicators": [
            'df["swing_h"] = df["High"].rolling(window=p["fib_lookback"]).max()',
            'df["swing_l"] = df["Low"].rolling(window=p["fib_lookback"]).min()',
            'df["fib_buy"] = df["swing_h"] - p["fib_level"] * (df["swing_h"] - df["swing_l"])',
            'df["fib_sell"] = df["swing_l"] + p["fib_level"] * (df["swing_h"] - df["swing_l"])',
        ],
        "long": 'uptrend & (df["Close"] > df["fib_buy"]) & (df["Close"].shift(1) <= df["fib_buy"].shift(1)) & (df["Close"] > df["Open"])',
        "short": 'downtrend & (df["Close"] < df["fib_sell"]) & (df["Close"].shift(1) >= df["fib_sell"].shift(1)) & (df["Close"] < df["Open"])',
    },
    # 28 — Support/Resistance bounce ──────────────────────────────────
    {
        "family": "support_resistance",
        "extra_params": {"sr_lookback": (20, 50)},
        "indicators": [
            'df["resistance"] = df["High"].rolling(window=p["sr_lookback"]).max().shift(1)',
            'df["support"] = df["Low"].rolling(window=p["sr_lookback"]).min().shift(1)',
        ],
        "long": 'uptrend & (df["Low"] <= df["support"] * 1.001) & (df["Close"] > df["support"]) & (df["Close"] > df["Open"])',
        "short": 'downtrend & (df["High"] >= df["resistance"] * 0.999) & (df["Close"] < df["resistance"]) & (df["Close"] < df["Open"])',
    },
    # 29 — Fake Breakout ──────────────────────────────────────────────
    {
        "family": "fake_breakout",
        "extra_params": {"fo_lookback": (15, 30)},
        "indicators": [
            'df["hi_prev"] = df["High"].rolling(window=p["fo_lookback"]).max().shift(1)',
            'df["lo_prev"] = df["Low"].rolling(window=p["fo_lookback"]).min().shift(1)',
            'df["swept_lo"] = (df["Low"] < df["lo_prev"]) & (df["Close"] > df["lo_prev"])',
            'df["swept_hi"] = (df["High"] > df["hi_prev"]) & (df["Close"] < df["hi_prev"])',
        ],
        "long": 'uptrend & df["swept_lo"] & (df["Close"] > df["Open"])',
        "short": 'downtrend & df["swept_hi"] & (df["Close"] < df["Open"])',
    },
    # 30 — Session breakout (London/NY) ───────────────────────────────
    {
        "family": "session_breakout",
        "extra_params": {"range_bars": (6, 18)},
        "indicators": [
            'df["hour"] = pd.to_datetime(df["time"]).dt.hour',
            'df["in_session"] = (df["hour"] >= 8) & (df["hour"] <= 16)',
            'df["range_hi"] = df["High"].rolling(window=p["range_bars"]).max().shift(1)',
            'df["range_lo"] = df["Low"].rolling(window=p["range_bars"]).min().shift(1)',
        ],
        "long": 'uptrend & df["in_session"] & (df["Close"] > df["range_hi"]) & (df["Close"].shift(1) <= df["range_hi"].shift(1))',
        "short": 'downtrend & df["in_session"] & (df["Close"] < df["range_lo"]) & (df["Close"].shift(1) >= df["range_lo"].shift(1))',
    },
    # 31 — Trend reversal (exhaustion) ────────────────────────────────
    {
        "family": "trend_reversal",
        "extra_params": {
            "rsi_period": (7, 21), "rsi_low": (25, 40), "rsi_high": (60, 75),
            "consec_bars": (3, 6),
        },
        "indicators": [
            'df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])',
            'df["down_count"] = (df["Close"] < df["Close"].shift(1)).rolling(window=p["consec_bars"]).sum()',
            'df["up_count"] = (df["Close"] > df["Close"].shift(1)).rolling(window=p["consec_bars"]).sum()',
        ],
        "long": 'uptrend & (df["down_count"] >= p["consec_bars"]) & (df["rsi"] < p["rsi_low"]) & (df["Close"] > df["Open"])',
        "short": 'downtrend & (df["up_count"] >= p["consec_bars"]) & (df["rsi"] > p["rsi_high"]) & (df["Close"] < df["Open"])',
    },
    # 32 — Multi-timeframe EMA (M5 + H1 approx) ──────────────────────
    {
        "family": "multi_tf_ema",
        "extra_params": {"h1_ema": (5, 20), "m5_ema": (10, 30)},
        "indicators": [
            'df["h1_ema"] = ta.trend.ema_indicator(df["Close"], window=12 * p["h1_ema"])',
            'df["m5_ema"] = ta.trend.ema_indicator(df["Close"], window=p["m5_ema"])',
        ],
        "long": '(df["Close"] > df["h1_ema"]) & (df["m5_ema"] > df["h1_ema"]) & (df["Low"] <= df["m5_ema"]) & (df["Close"] > df["m5_ema"])',
        "short": '(df["Close"] < df["h1_ema"]) & (df["m5_ema"] < df["h1_ema"]) & (df["High"] >= df["m5_ema"]) & (df["Close"] < df["m5_ema"])',
    },
    # 33 — Price action doji + confirmation ───────────────────────────
    {
        "family": "price_action_doji",
        "extra_params": {"doji_ratio": (0.1, 0.3), "confirm_ratio": (1.0, 2.0)},
        "indicators": [
            'df["body"] = abs(df["Close"] - df["Open"])',
            'df["candle_range"] = (df["High"] - df["Low"]).clip(lower=0.01)',
            'df["is_doji"] = df["body"] < p["doji_ratio"] * df["candle_range"]',
            'df["prev_doji"] = df["is_doji"].shift(1).fillna(False)',
            'df["confirm_bull"] = (df["Close"] > df["Open"]) & (df["body"] > p["confirm_ratio"] * df["body"].shift(1).clip(lower=0.01))',
            'df["confirm_bear"] = (df["Close"] < df["Open"]) & (df["body"] > p["confirm_ratio"] * df["body"].shift(1).clip(lower=0.01))',
        ],
        "long": 'uptrend & df["prev_doji"] & df["confirm_bull"]',
        "short": 'downtrend & df["prev_doji"] & df["confirm_bear"]',
    },
    # 34 — Stochastic RSI ─────────────────────────────────────────────
    {
        "family": "stoch_rsi",
        "extra_params": {
            "srsi_period": (7, 21), "srsi_low": (10, 30), "srsi_high": (70, 90),
        },
        "indicators": [
            'df["rsi"] = ta.momentum.rsi(df["Close"], window=p["srsi_period"])',
            'df["rsi_min"] = df["rsi"].rolling(window=p["srsi_period"]).min()',
            'df["rsi_max"] = df["rsi"].rolling(window=p["srsi_period"]).max()',
            'df["stoch_rsi"] = ((df["rsi"] - df["rsi_min"]) / (df["rsi_max"] - df["rsi_min"] + 0.0001)) * 100',
        ],
        "long": 'uptrend & (df["stoch_rsi"] > p["srsi_low"]) & (df["stoch_rsi"].shift(1) <= p["srsi_low"])',
        "short": 'downtrend & (df["stoch_rsi"] < p["srsi_high"]) & (df["stoch_rsi"].shift(1) >= p["srsi_high"])',
    },
    # 35 — VWAP deviation ─────────────────────────────────────────────
    {
        "family": "vwap_deviation",
        "extra_params": {"vwap_period": (15, 40), "vwap_std": (1.0, 2.5)},
        "indicators": [
            'df["typical"] = (df["High"] + df["Low"] + df["Close"]) / 3',
            'df["vwap"] = (df["typical"] * df["Volume"]).rolling(window=p["vwap_period"]).sum() / df["Volume"].rolling(window=p["vwap_period"]).sum().clip(lower=1)',
            'df["vwap_sd"] = df["typical"].rolling(window=p["vwap_period"]).std()',
            'df["vwap_lo"] = df["vwap"] - p["vwap_std"] * df["vwap_sd"]',
            'df["vwap_hi"] = df["vwap"] + p["vwap_std"] * df["vwap_sd"]',
        ],
        "long": 'uptrend & (df["Close"] <= df["vwap_lo"]) & (df["Close"] > df["Close"].shift(1))',
        "short": 'downtrend & (df["Close"] >= df["vwap_hi"]) & (df["Close"] < df["Close"].shift(1))',
    },
    # 36 — Range trading (mean reversion at boundaries) ───────────────
    {
        "family": "range_trading",
        "extra_params": {"range_period": (20, 50), "range_pct": (0.2, 0.4)},
        "indicators": [
            'df["hi_range"] = df["High"].rolling(window=p["range_period"]).max()',
            'df["lo_range"] = df["Low"].rolling(window=p["range_period"]).min()',
            'df["rng_width"] = df["hi_range"] - df["lo_range"]',
            'df["near_low"] = df["Close"] < df["lo_range"] + p["range_pct"] * df["rng_width"]',
            'df["near_high"] = df["Close"] > df["hi_range"] - p["range_pct"] * df["rng_width"]',
        ],
        "long": 'uptrend & df["near_low"] & (df["Close"] > df["Open"]) & (df["Close"] > df["Close"].shift(1))',
        "short": 'downtrend & df["near_high"] & (df["Close"] < df["Open"]) & (df["Close"] < df["Close"].shift(1))',
    },
    # 37 — Liquidity sweep (stop hunt reversal) ───────────────────────
    {
        "family": "liquidity_sweep",
        "extra_params": {"sweep_lookback": (10, 30), "wick_min": (0.5, 1.5)},
        "indicators": [
            'df["prev_lo"] = df["Low"].rolling(window=p["sweep_lookback"]).min().shift(1)',
            'df["prev_hi"] = df["High"].rolling(window=p["sweep_lookback"]).max().shift(1)',
            'df["lo_wick"] = df[["Close", "Open"]].min(axis=1) - df["Low"]',
            'df["hi_wick"] = df["High"] - df[["Close", "Open"]].max(axis=1)',
            'df["swept_lo"] = (df["Low"] < df["prev_lo"]) & (df["Close"] > df["prev_lo"])',
            'df["swept_hi"] = (df["High"] > df["prev_hi"]) & (df["Close"] < df["prev_hi"])',
        ],
        "long": 'uptrend & df["swept_lo"] & (df["lo_wick"] > p["wick_min"] * df["ATR"]) & (df["Close"] > df["Open"])',
        "short": 'downtrend & df["swept_hi"] & (df["hi_wick"] > p["wick_min"] * df["ATR"]) & (df["Close"] < df["Open"])',
    },
    # 38 — Gap momentum ───────────────────────────────────────────────
    {
        "family": "gap_scalping",
        "extra_params": {"gap_pct": (0.05, 0.2)},
        "indicators": [
            'df["gap"] = df["Open"] - df["Close"].shift(1)',
            'df["gap_pct_val"] = abs(df["gap"]) / df["Close"].shift(1).clip(lower=1) * 100',
            'df["gap_up"] = df["gap"] > 0',
            'df["gap_down"] = df["gap"] < 0',
        ],
        "long": 'uptrend & df["gap_up"] & (df["gap_pct_val"] > p["gap_pct"]) & (df["Close"] > df["Open"])',
        "short": 'downtrend & df["gap_down"] & (df["gap_pct_val"] > p["gap_pct"]) & (df["Close"] < df["Open"])',
    },
    # 39 — Multi-timeframe RSI (M5 entry, H1 filter) ─────────────────
    {
        "family": "multi_tf_rsi",
        "extra_params": {"rsi_m5": (7, 14), "rsi_h1_mult": (10, 20)},
        "indicators": [
            'df["rsi_fast"] = ta.momentum.rsi(df["Close"], window=p["rsi_m5"])',
            'df["rsi_slow"] = ta.momentum.rsi(df["Close"], window=12 * p["rsi_h1_mult"])',
        ],
        "long": 'uptrend & (df["rsi_slow"] > 50) & (df["rsi_fast"] < 30) & (df["rsi_fast"].shift(1) >= 30)',
        "short": 'downtrend & (df["rsi_slow"] < 50) & (df["rsi_fast"] > 70) & (df["rsi_fast"].shift(1) <= 70)',
    },
    # 40 — Williams %R ────────────────────────────────────────────────
    {
        "family": "williams_percent_r",
        "extra_params": {"wr_period": (10, 21), "wr_low": (-90, -70), "wr_high": (-30, -10)},
        "indicators": [
            'df["wr"] = ta.momentum.williams_r(df["High"], df["Low"], df["Close"], lbp=p["wr_period"])',
        ],
        "long": 'uptrend & (df["wr"] > p["wr_low"]) & (df["wr"].shift(1) <= p["wr_low"])',
        "short": 'downtrend & (df["wr"] < p["wr_high"]) & (df["wr"].shift(1) >= p["wr_high"])',
    },
    # ═══════════════════════════════════════════════════════════════════
    #  HYBRID / COMBO templates — mix multiple indicators with OR logic
    # ═══════════════════════════════════════════════════════════════════
    # 41 — RSI + Stochastic combo (OR) ────────────────────────────────
    {
        "family": "hybrid_rsi_stoch",
        "extra_params": {
            "rsi_period": (7, 21), "rsi_low": (20, 40), "rsi_high": (60, 80),
            "stoch_k": (5, 21), "stoch_d": (3, 7),
        },
        "indicators": [
            'df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])',
            'df["sk"] = ta.momentum.stoch(df["High"], df["Low"], df["Close"], window=p["stoch_k"], smooth_window=p["stoch_d"])',
            'df["sd"] = ta.momentum.stoch_signal(df["High"], df["Low"], df["Close"], window=p["stoch_k"], smooth_window=p["stoch_d"])',
        ],
        "long": 'uptrend & (((df["rsi"] < p["rsi_low"]) & (df["rsi"].shift(1) >= p["rsi_low"])) | ((df["sk"] > df["sd"]) & (df["sk"].shift(1) <= df["sd"].shift(1)) & (df["sk"] < 25)))',
        "short": 'downtrend & (((df["rsi"] > p["rsi_high"]) & (df["rsi"].shift(1) <= p["rsi_high"])) | ((df["sk"] < df["sd"]) & (df["sk"].shift(1) >= df["sd"].shift(1)) & (df["sk"] > 75)))',
    },
    # 42 — MACD + Bollinger combo (OR) ────────────────────────────────
    {
        "family": "hybrid_macd_bb",
        "extra_params": {
            "macd_fast": (8, 15), "macd_slow": (20, 30), "macd_sign": (7, 12),
            "bb_period": (15, 30), "bb_std": (1.5, 3.0),
        },
        "indicators": [
            'df["macd_h"] = ta.trend.macd_diff(df["Close"], window_slow=p["macd_slow"], window_fast=p["macd_fast"], window_sign=p["macd_sign"])',
            'df["bb_h"] = ta.volatility.bollinger_hband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])',
            'df["bb_l"] = ta.volatility.bollinger_lband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])',
        ],
        "long": 'uptrend & (((df["macd_h"] > 0) & (df["macd_h"].shift(1) <= 0)) | ((df["Close"] <= df["bb_l"]) & (df["Close"].shift(1) > df["bb_l"].shift(1))))',
        "short": 'downtrend & (((df["macd_h"] < 0) & (df["macd_h"].shift(1) >= 0)) | ((df["Close"] >= df["bb_h"]) & (df["Close"].shift(1) < df["bb_h"].shift(1))))',
    },
    # 43 — Ichimoku + RSI combo ───────────────────────────────────────
    {
        "family": "hybrid_ichimoku_rsi",
        "extra_params": {
            "ichi_conv": (7, 12), "ichi_base": (20, 30), "ichi_span": (40, 60),
            "rsi_period": (7, 21), "rsi_low": (25, 40), "rsi_high": (60, 75),
        },
        "indicators": [
            'ichi = ta.trend.IchimokuIndicator(df["High"], df["Low"], window1=p["ichi_conv"], window2=p["ichi_base"], window3=p["ichi_span"])',
            'df["ichi_a"] = ichi.ichimoku_a()',
            'df["ichi_b"] = ichi.ichimoku_b()',
            'df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])',
        ],
        "long": 'uptrend & (df["Close"] > df["ichi_a"]) & (df["Close"] > df["ichi_b"]) & (df["rsi"] < p["rsi_low"]) & (df["rsi"].shift(1) >= p["rsi_low"])',
        "short": 'downtrend & (df["Close"] < df["ichi_a"]) & (df["Close"] < df["ichi_b"]) & (df["rsi"] > p["rsi_high"]) & (df["rsi"].shift(1) <= p["rsi_high"])',
    },
    # 44 — Fibonacci + MACD combo ─────────────────────────────────────
    {
        "family": "hybrid_fib_macd",
        "extra_params": {
            "fib_lookback": (20, 60), "fib_level": (0.3, 0.7),
            "macd_fast": (8, 15), "macd_slow": (20, 30), "macd_sign": (7, 12),
        },
        "indicators": [
            'df["swing_h"] = df["High"].rolling(window=p["fib_lookback"]).max()',
            'df["swing_l"] = df["Low"].rolling(window=p["fib_lookback"]).min()',
            'df["fib_buy"] = df["swing_h"] - p["fib_level"] * (df["swing_h"] - df["swing_l"])',
            'df["fib_sell"] = df["swing_l"] + p["fib_level"] * (df["swing_h"] - df["swing_l"])',
            'df["fib_cross_up"] = (df["Close"] > df["fib_buy"]) & (df["Close"].shift(1) <= df["fib_buy"].shift(1))',
            'df["fib_cross_dn"] = (df["Close"] < df["fib_sell"]) & (df["Close"].shift(1) >= df["fib_sell"].shift(1))',
            'df["macd_h"] = ta.trend.macd_diff(df["Close"], window_slow=p["macd_slow"], window_fast=p["macd_fast"], window_sign=p["macd_sign"])',
        ],
        "long": 'uptrend & df["fib_cross_up"] & (df["macd_h"] > df["macd_h"].shift(1))',
        "short": 'downtrend & df["fib_cross_dn"] & (df["macd_h"] < df["macd_h"].shift(1))',
    },
    # 45 — Volume + RSI + BB triple combo (OR) ────────────────────────
    {
        "family": "hybrid_vol_rsi_bb",
        "extra_params": {
            "rsi_period": (7, 21), "rsi_low": (20, 40), "rsi_high": (60, 80),
            "bb_period": (15, 30), "bb_std": (1.5, 3.0), "vol_mult": (1.5, 3.0),
        },
        "indicators": [
            'df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])',
            'df["bb_l"] = ta.volatility.bollinger_lband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])',
            'df["bb_h"] = ta.volatility.bollinger_hband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])',
            'df["vol_ma"] = df["Volume"].rolling(window=20).mean()',
            'df["vol_spike"] = df["Volume"] > p["vol_mult"] * df["vol_ma"]',
        ],
        "long": 'uptrend & (((df["rsi"] < p["rsi_low"]) & (df["rsi"].shift(1) >= p["rsi_low"])) | ((df["Close"] <= df["bb_l"]) & (df["Close"].shift(1) > df["bb_l"].shift(1))) | (df["vol_spike"] & (df["Close"] > df["Open"]) & (df["Close"] > df["Close"].shift(1))))',
        "short": 'downtrend & (((df["rsi"] > p["rsi_high"]) & (df["rsi"].shift(1) <= p["rsi_high"])) | ((df["Close"] >= df["bb_h"]) & (df["Close"].shift(1) < df["bb_h"].shift(1))) | (df["vol_spike"] & (df["Close"] < df["Open"]) & (df["Close"] < df["Close"].shift(1))))',
    },
    # 46 — Supertrend + RSI combo (OR) ────────────────────────────────
    {
        "family": "hybrid_supertrend_rsi",
        "extra_params": {
            "st_mult": (1.5, 3.0), "st_period": (7, 15),
            "rsi_period": (7, 21), "rsi_low": (20, 40), "rsi_high": (60, 80),
        },
        "indicators": [
            'df["st_atr"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p["st_period"])',
            'df["hl2"] = (df["High"] + df["Low"]) / 2',
            'df["st_upper"] = df["hl2"] + p["st_mult"] * df["st_atr"]',
            'df["st_lower"] = df["hl2"] - p["st_mult"] * df["st_atr"]',
            'df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])',
        ],
        "long": 'uptrend & (((df["Close"] > df["st_upper"]) & (df["Close"].shift(1) <= df["st_upper"].shift(1))) | ((df["rsi"] < p["rsi_low"]) & (df["rsi"].shift(1) >= p["rsi_low"])))',
        "short": 'downtrend & (((df["Close"] < df["st_lower"]) & (df["Close"].shift(1) >= df["st_lower"].shift(1))) | ((df["rsi"] > p["rsi_high"]) & (df["rsi"].shift(1) <= p["rsi_high"])))',
    },
    # 47 — Session + Volume combo ─────────────────────────────────────
    {
        "family": "hybrid_session_volume",
        "extra_params": {"range_bars": (6, 18), "vol_mult": (1.2, 2.5)},
        "indicators": [
            'df["hour"] = pd.to_datetime(df["time"]).dt.hour',
            'df["in_session"] = (df["hour"] >= 8) & (df["hour"] <= 16)',
            'df["range_hi"] = df["High"].rolling(window=p["range_bars"]).max().shift(1)',
            'df["range_lo"] = df["Low"].rolling(window=p["range_bars"]).min().shift(1)',
            'df["vol_ma"] = df["Volume"].rolling(window=20).mean()',
            'df["vol_ok"] = df["Volume"] > p["vol_mult"] * df["vol_ma"]',
        ],
        "long": 'uptrend & df["in_session"] & df["vol_ok"] & (df["Close"] > df["range_hi"])',
        "short": 'downtrend & df["in_session"] & df["vol_ok"] & (df["Close"] < df["range_lo"])',
    },
    # 48 — Triple OR: RSI | MACD | ATR expansion ─────────────────────
    {
        "family": "hybrid_triple_or",
        "extra_params": {
            "rsi_period": (7, 21), "rsi_low": (20, 40), "rsi_high": (60, 80),
            "macd_fast": (8, 15), "macd_slow": (20, 30), "macd_sign": (7, 12),
            "atr_ratio": (1.2, 2.0),
        },
        "indicators": [
            'df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])',
            'df["macd_h"] = ta.trend.macd_diff(df["Close"], window_slow=p["macd_slow"], window_fast=p["macd_fast"], window_sign=p["macd_sign"])',
            'df["atr_ma"] = df["ATR"].rolling(window=20).mean()',
            'df["atr_exp"] = df["ATR"] > p["atr_ratio"] * df["atr_ma"]',
        ],
        "long": 'uptrend & (((df["rsi"] < p["rsi_low"]) & (df["rsi"].shift(1) >= p["rsi_low"])) | ((df["macd_h"] > 0) & (df["macd_h"].shift(1) <= 0)) | (df["atr_exp"] & (~df["atr_exp"].shift(1).fillna(False)) & (df["Close"] > df["Open"])))',
        "short": 'downtrend & (((df["rsi"] > p["rsi_high"]) & (df["rsi"].shift(1) <= p["rsi_high"])) | ((df["macd_h"] < 0) & (df["macd_h"].shift(1) >= 0)) | (df["atr_exp"] & (~df["atr_exp"].shift(1).fillna(False)) & (df["Close"] < df["Open"])))',
    },
    # 49 — Stoch + MACD + EMA bounce (2 of 3 must agree) ─────────────
    {
        "family": "hybrid_2of3",
        "extra_params": {
            "stoch_k": (5, 21), "stoch_d": (3, 7),
            "macd_fast": (8, 15), "macd_slow": (20, 30), "macd_sign": (7, 12),
            "ema_mid": (15, 30),
        },
        "indicators": [
            'df["sk"] = ta.momentum.stoch(df["High"], df["Low"], df["Close"], window=p["stoch_k"], smooth_window=p["stoch_d"])',
            'df["macd_h"] = ta.trend.macd_diff(df["Close"], window_slow=p["macd_slow"], window_fast=p["macd_fast"], window_sign=p["macd_sign"])',
            'df["ema_m"] = ta.trend.ema_indicator(df["Close"], window=p["ema_mid"])',
            'df["c_stoch_l"] = (df["sk"] < 25).astype(int)',
            'df["c_macd_l"] = ((df["macd_h"] > 0) & (df["macd_h"].shift(1) <= 0)).astype(int)',
            'df["c_ema_l"] = ((df["Low"] <= df["ema_m"]) & (df["Close"] > df["ema_m"])).astype(int)',
            'df["score_l"] = df["c_stoch_l"] + df["c_macd_l"] + df["c_ema_l"]',
            'df["c_stoch_s"] = (df["sk"] > 75).astype(int)',
            'df["c_macd_s"] = ((df["macd_h"] < 0) & (df["macd_h"].shift(1) >= 0)).astype(int)',
            'df["c_ema_s"] = ((df["High"] >= df["ema_m"]) & (df["Close"] < df["ema_m"])).astype(int)',
            'df["score_s"] = df["c_stoch_s"] + df["c_macd_s"] + df["c_ema_s"]',
        ],
        "long": 'uptrend & (df["score_l"] >= 2)',
        "short": 'downtrend & (df["score_s"] >= 2)',
    },
    # 50 — Keltner + Donchian + BB triple channel (AND) ───────────────
    {
        "family": "hybrid_triple_channel",
        "extra_params": {
            "kc_period": (15, 30), "kc_mult": (1.5, 3.0),
            "bb_period": (15, 30), "bb_std": (1.5, 3.0),
            "dc_period": (10, 30),
        },
        "indicators": [
            'df["kc_mid"] = ta.trend.ema_indicator(df["Close"], window=p["kc_period"])',
            'df["kc_atr"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p["kc_period"])',
            'df["kc_h"] = df["kc_mid"] + p["kc_mult"] * df["kc_atr"]',
            'df["kc_l"] = df["kc_mid"] - p["kc_mult"] * df["kc_atr"]',
            'df["bb_h"] = ta.volatility.bollinger_hband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])',
            'df["bb_l"] = ta.volatility.bollinger_lband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])',
            'df["dc_h"] = df["High"].rolling(window=p["dc_period"]).max().shift(1)',
            'df["dc_l"] = df["Low"].rolling(window=p["dc_period"]).min().shift(1)',
        ],
        "long": 'uptrend & (df["Close"] > df["kc_h"]) & (df["Close"] > df["bb_h"]) & (df["Close"] > df["dc_h"])',
        "short": 'downtrend & (df["Close"] < df["kc_l"]) & (df["Close"] < df["bb_l"]) & (df["Close"] < df["dc_l"])',
    },
    # ═══════════════════════════════════════════════════════════════════
    #  EXTENDED templates — more market approaches for diversity
    # ═══════════════════════════════════════════════════════════════════
    # 51 — Hammer / Shooting Star (price action) ─────────────────────
    {
        "family": "hammer_star",
        "extra_params": {"wick_mult": (2.0, 4.0), "body_max_pct": (0.2, 0.4)},
        "indicators": [
            'df["body"] = abs(df["Close"] - df["Open"]).clip(lower=0.01)',
            'df["full_range"] = (df["High"] - df["Low"]).clip(lower=0.01)',
            'df["lo_wick"] = df[["Close", "Open"]].min(axis=1) - df["Low"]',
            'df["hi_wick"] = df["High"] - df[["Close", "Open"]].max(axis=1)',
            'df["body_pct"] = df["body"] / df["full_range"]',
        ],
        "long": 'uptrend & (df["lo_wick"] > p["wick_mult"] * df["body"]) & (df["body_pct"] < p["body_max_pct"]) & (df["Close"] > df["Open"])',
        "short": 'downtrend & (df["hi_wick"] > p["wick_mult"] * df["body"]) & (df["body_pct"] < p["body_max_pct"]) & (df["Close"] < df["Open"])',
    },
    # 52 — Market Profile Value Area ──────────────────────────────────
    {
        "family": "market_profile",
        "extra_params": {"mp_period": (48, 144), "va_pct": (0.25, 0.40)},
        "indicators": [
            'df["poc"] = df["Close"].rolling(window=p["mp_period"]).median()',
            'df["mp_std"] = df["Close"].rolling(window=p["mp_period"]).std()',
            'df["va_high"] = df["poc"] + p["va_pct"] * df["mp_std"] * 2',
            'df["va_low"] = df["poc"] - p["va_pct"] * df["mp_std"] * 2',
        ],
        "long": 'uptrend & (df["Close"] <= df["va_low"]) & (df["Close"] > df["Close"].shift(1)) & (df["Close"] > df["Open"])',
        "short": 'downtrend & (df["Close"] >= df["va_high"]) & (df["Close"] < df["Close"].shift(1)) & (df["Close"] < df["Open"])',
    },
    # 53 — Momentum Breakout (strong candle + volume) ─────────────────
    {
        "family": "momentum_breakout",
        "extra_params": {"body_atr_mult": (1.2, 2.5), "vol_mult": (1.3, 2.5)},
        "indicators": [
            'df["body"] = abs(df["Close"] - df["Open"])',
            'df["vol_ma"] = df["Volume"].rolling(window=20).mean()',
            'df["big_body"] = df["body"] > p["body_atr_mult"] * df["ATR"]',
            'df["big_vol"] = df["Volume"] > p["vol_mult"] * df["vol_ma"]',
        ],
        "long": 'uptrend & df["big_body"] & df["big_vol"] & (df["Close"] > df["Open"]) & (df["Close"] > df["High"].shift(1))',
        "short": 'downtrend & df["big_body"] & df["big_vol"] & (df["Close"] < df["Open"]) & (df["Close"] < df["Low"].shift(1))',
    },
    # 54 — London Open Breakout (08:00-10:00 UTC) ─────────────────────
    {
        "family": "london_open",
        "extra_params": {"pre_bars": (6, 18), "atr_filter": (0.8, 1.5)},
        "indicators": [
            'df["hour"] = pd.to_datetime(df["time"]).dt.hour',
            'df["london"] = (df["hour"] >= 8) & (df["hour"] <= 10)',
            'df["pre_hi"] = df["High"].rolling(window=p["pre_bars"]).max().shift(1)',
            'df["pre_lo"] = df["Low"].rolling(window=p["pre_bars"]).min().shift(1)',
            'df["atr_ma"] = df["ATR"].rolling(window=20).mean()',
            'df["vol_ok"] = df["ATR"] > p["atr_filter"] * df["atr_ma"]',
        ],
        "long": 'uptrend & df["london"] & df["vol_ok"] & (df["Close"] > df["pre_hi"]) & (df["Close"].shift(1) <= df["pre_hi"].shift(1))',
        "short": 'downtrend & df["london"] & df["vol_ok"] & (df["Close"] < df["pre_lo"]) & (df["Close"].shift(1) >= df["pre_lo"].shift(1))',
    },
    # 55 — NY Open Breakout (13:00-15:00 UTC) ─────────────────────────
    {
        "family": "ny_open",
        "extra_params": {"pre_bars": (6, 18), "atr_filter": (0.8, 1.5)},
        "indicators": [
            'df["hour"] = pd.to_datetime(df["time"]).dt.hour',
            'df["ny"] = (df["hour"] >= 13) & (df["hour"] <= 15)',
            'df["pre_hi"] = df["High"].rolling(window=p["pre_bars"]).max().shift(1)',
            'df["pre_lo"] = df["Low"].rolling(window=p["pre_bars"]).min().shift(1)',
            'df["atr_ma"] = df["ATR"].rolling(window=20).mean()',
            'df["vol_ok"] = df["ATR"] > p["atr_filter"] * df["atr_ma"]',
        ],
        "long": 'uptrend & df["ny"] & df["vol_ok"] & (df["Close"] > df["pre_hi"]) & (df["Close"].shift(1) <= df["pre_hi"].shift(1))',
        "short": 'downtrend & df["ny"] & df["vol_ok"] & (df["Close"] < df["pre_lo"]) & (df["Close"].shift(1) >= df["pre_lo"].shift(1))',
    },
    # 56 — Double Bottom / Double Top ─────────────────────────────────
    {
        "family": "double_pattern",
        "extra_params": {"lookback": (15, 40), "tolerance": (0.001, 0.003)},
        "indicators": [
            'df["lo_prev"] = df["Low"].rolling(window=p["lookback"]).min()',
            'df["hi_prev"] = df["High"].rolling(window=p["lookback"]).max()',
            'df["lo_recent"] = df["Low"].rolling(window=p["lookback"]//2).min()',
            'df["hi_recent"] = df["High"].rolling(window=p["lookback"]//2).max()',
            'df["dbl_bot"] = abs(df["lo_recent"] - df["lo_prev"]) / df["Close"].clip(lower=1) < p["tolerance"]',
            'df["dbl_top"] = abs(df["hi_recent"] - df["hi_prev"]) / df["Close"].clip(lower=1) < p["tolerance"]',
        ],
        "long": 'uptrend & df["dbl_bot"] & (df["Close"] > df["Open"]) & (df["Close"] > df["Close"].shift(1))',
        "short": 'downtrend & df["dbl_top"] & (df["Close"] < df["Open"]) & (df["Close"] < df["Close"].shift(1))',
    },
    # 57 — RSI Divergence (price vs RSI) ──────────────────────────────
    {
        "family": "rsi_divergence",
        "extra_params": {"rsi_period": (7, 21), "div_lookback": (5, 15)},
        "indicators": [
            'df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])',
            'df["price_lo"] = df["Close"].rolling(window=p["div_lookback"]).min()',
            'df["rsi_lo"] = df["rsi"].rolling(window=p["div_lookback"]).min()',
            'df["price_hi"] = df["Close"].rolling(window=p["div_lookback"]).max()',
            'df["rsi_hi"] = df["rsi"].rolling(window=p["div_lookback"]).max()',
            'df["bull_div"] = (df["Close"] <= df["price_lo"] * 1.001) & (df["rsi"] > df["rsi_lo"] + 5)',
            'df["bear_div"] = (df["Close"] >= df["price_hi"] * 0.999) & (df["rsi"] < df["rsi_hi"] - 5)',
        ],
        "long": 'uptrend & df["bull_div"] & (df["Close"] > df["Open"])',
        "short": 'downtrend & df["bear_div"] & (df["Close"] < df["Open"])',
    },
    # 58 — Inside Bar Breakout ────────────────────────────────────────
    {
        "family": "inside_bar",
        "extra_params": {"atr_filter": (0.8, 1.5)},
        "indicators": [
            'df["inside"] = (df["High"] < df["High"].shift(1)) & (df["Low"] > df["Low"].shift(1))',
            'df["was_inside"] = df["inside"].shift(1).fillna(False)',
            'df["mother_hi"] = df["High"].shift(2)',
            'df["mother_lo"] = df["Low"].shift(2)',
            'df["atr_ma"] = df["ATR"].rolling(window=20).mean()',
            'df["vol_ok"] = df["ATR"] > p["atr_filter"] * df["atr_ma"]',
        ],
        "long": 'uptrend & df["was_inside"] & (df["Close"] > df["mother_hi"]) & df["vol_ok"]',
        "short": 'downtrend & df["was_inside"] & (df["Close"] < df["mother_lo"]) & df["vol_ok"]',
    },
    # 59 — Three White Soldiers / Three Black Crows ───────────────────
    {
        "family": "three_soldiers",
        "extra_params": {"min_body_atr": (0.3, 0.7)},
        "indicators": [
            'df["body"] = abs(df["Close"] - df["Open"])',
            'df["bull"] = (df["Close"] > df["Open"]).astype(int)',
            'df["bear"] = (df["Close"] < df["Open"]).astype(int)',
            'df["three_bull"] = (df["bull"] + df["bull"].shift(1) + df["bull"].shift(2)) == 3',
            'df["three_bear"] = (df["bear"] + df["bear"].shift(1) + df["bear"].shift(2)) == 3',
            'df["rising"] = (df["Close"] > df["Close"].shift(1)) & (df["Close"].shift(1) > df["Close"].shift(2))',
            'df["falling"] = (df["Close"] < df["Close"].shift(1)) & (df["Close"].shift(1) < df["Close"].shift(2))',
            'df["body_ok"] = df["body"] > p["min_body_atr"] * df["ATR"]',
        ],
        "long": 'uptrend & df["three_bull"] & df["rising"] & df["body_ok"]',
        "short": 'downtrend & df["three_bear"] & df["falling"] & df["body_ok"]',
    },
    # 60 — Squeeze Momentum (BB inside KC) ────────────────────────────
    {
        "family": "squeeze_momentum",
        "extra_params": {
            "bb_period": (15, 30), "bb_std": (1.5, 2.5),
            "kc_period": (15, 30), "kc_mult": (1.0, 2.0),
        },
        "indicators": [
            'df["bb_h"] = ta.volatility.bollinger_hband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])',
            'df["bb_l"] = ta.volatility.bollinger_lband(df["Close"], window=p["bb_period"], window_dev=p["bb_std"])',
            'df["kc_mid"] = ta.trend.ema_indicator(df["Close"], window=p["kc_period"])',
            'df["kc_atr"] = ta.volatility.average_true_range(df["High"], df["Low"], df["Close"], window=p["kc_period"])',
            'df["kc_h"] = df["kc_mid"] + p["kc_mult"] * df["kc_atr"]',
            'df["kc_l"] = df["kc_mid"] - p["kc_mult"] * df["kc_atr"]',
            'df["in_squeeze"] = (df["bb_l"] > df["kc_l"]) & (df["bb_h"] < df["kc_h"])',
            'df["was_squeeze"] = df["in_squeeze"].shift(1).fillna(False)',
            'df["mom"] = df["Close"] - ta.trend.ema_indicator(df["Close"], window=p["bb_period"])',
        ],
        "long": 'uptrend & df["was_squeeze"] & ~df["in_squeeze"] & (df["mom"] > 0) & (df["mom"] > df["mom"].shift(1))',
        "short": 'downtrend & df["was_squeeze"] & ~df["in_squeeze"] & (df["mom"] < 0) & (df["mom"] < df["mom"].shift(1))',
    },
    # 61 — ADX + DI Trend Strength ────────────────────────────────────
    {
        "family": "adx_trend",
        "extra_params": {"adx_period": (10, 20), "adx_strong": (25, 40), "rsi_period": (7, 14)},
        "indicators": [
            'df["adx"] = ta.trend.adx(df["High"], df["Low"], df["Close"], window=p["adx_period"])',
            'df["di_p"] = ta.trend.adx_pos(df["High"], df["Low"], df["Close"], window=p["adx_period"])',
            'df["di_n"] = ta.trend.adx_neg(df["High"], df["Low"], df["Close"], window=p["adx_period"])',
            'df["rsi"] = ta.momentum.rsi(df["Close"], window=p["rsi_period"])',
        ],
        "long": 'uptrend & (df["adx"] > p["adx_strong"]) & (df["di_p"] > df["di_n"]) & (df["rsi"] < 40) & (df["rsi"].shift(1) >= 40)',
        "short": 'downtrend & (df["adx"] > p["adx_strong"]) & (df["di_n"] > df["di_p"]) & (df["rsi"] > 60) & (df["rsi"].shift(1) <= 60)',
    },
    # 62 — Pivot Points ───────────────────────────────────────────────
    {
        "family": "pivot_points",
        "extra_params": {"pivot_period": (48, 144)},
        "indicators": [
            'df["pivot_h"] = df["High"].rolling(window=p["pivot_period"]).max().shift(1)',
            'df["pivot_l"] = df["Low"].rolling(window=p["pivot_period"]).min().shift(1)',
            'df["pivot_c"] = df["Close"].rolling(window=p["pivot_period"]).mean().shift(1)',
            'df["pp"] = (df["pivot_h"] + df["pivot_l"] + df["pivot_c"]) / 3',
            'df["r1"] = 2 * df["pp"] - df["pivot_l"]',
            'df["s1"] = 2 * df["pp"] - df["pivot_h"]',
        ],
        "long": 'uptrend & (df["Close"] > df["pp"]) & (df["Close"].shift(1) <= df["pp"].shift(1)) & (df["Close"] > df["Open"])',
        "short": 'downtrend & (df["Close"] < df["pp"]) & (df["Close"].shift(1) >= df["pp"].shift(1)) & (df["Close"] < df["Open"])',
    },
    # 63 — OBV Divergence (On-Balance Volume) ─────────────────────────
    {
        "family": "obv_divergence",
        "extra_params": {"obv_ema": (10, 30), "lookback": (10, 25)},
        "indicators": [
            'df["obv"] = (np.sign(df["Close"].diff()) * df["Volume"]).cumsum()',
            'df["obv_ema"] = ta.trend.ema_indicator(df["obv"], window=p["obv_ema"])',
            'df["price_rising"] = df["Close"] > df["Close"].shift(p["lookback"])',
            'df["obv_rising"] = df["obv_ema"] > df["obv_ema"].shift(p["lookback"])',
        ],
        "long": 'uptrend & (~df["price_rising"]) & df["obv_rising"] & (df["Close"] > df["Open"])',
        "short": 'downtrend & df["price_rising"] & (~df["obv_rising"]) & (df["Close"] < df["Open"])',
    },
    # 64 — CCI Mean Reversion ─────────────────────────────────────────
    {
        "family": "cci_reversion",
        "extra_params": {"cci_period": (10, 25), "cci_low": (-150, -80), "cci_high": (80, 150)},
        "indicators": [
            'df["cci"] = ta.trend.cci(df["High"], df["Low"], df["Close"], window=p["cci_period"])',
        ],
        "long": 'uptrend & (df["cci"] > p["cci_low"]) & (df["cci"].shift(1) <= p["cci_low"]) & (df["Close"] > df["Open"])',
        "short": 'downtrend & (df["cci"] < p["cci_high"]) & (df["cci"].shift(1) >= p["cci_high"]) & (df["Close"] < df["Open"])',
    },
    # 65 — Trendline Break (regression channel) ───────────────────────
    {
        "family": "regression_break",
        "extra_params": {"reg_period": (20, 60), "std_mult": (1.5, 2.5)},
        "indicators": [
            'df["reg_mean"] = df["Close"].rolling(window=p["reg_period"]).mean()',
            'df["reg_std"] = df["Close"].rolling(window=p["reg_period"]).std()',
            'df["reg_upper"] = df["reg_mean"] + p["std_mult"] * df["reg_std"]',
            'df["reg_lower"] = df["reg_mean"] - p["std_mult"] * df["reg_std"]',
        ],
        "long": 'uptrend & (df["Close"] <= df["reg_lower"]) & (df["Close"] > df["Close"].shift(1)) & (df["Close"] > df["Open"])',
        "short": 'downtrend & (df["Close"] >= df["reg_upper"]) & (df["Close"] < df["Close"].shift(1)) & (df["Close"] < df["Open"])',
    },
    # 66 — Heikin-Ashi trend flip ──────────────────────────────────────
    {
        "family": "heikin_ashi_trend",
        "extra_params": {},
        "indicators": [
            'df["ha_close"] = (df["Open"] + df["High"] + df["Low"] + df["Close"]) / 4',
            'df["ha_open"] = (df["Open"].shift(1) + df["Close"].shift(1)) / 2',
        ],
        "long": 'uptrend & (df["ha_close"] > df["ha_open"]) & (df["ha_close"].shift(1) <= df["ha_open"].shift(1))',
        "short": 'downtrend & (df["ha_close"] < df["ha_open"]) & (df["ha_close"].shift(1) >= df["ha_open"].shift(1))',
    },
    # 67 — Money Flow Index reversion ──────────────────────────────────
    {
        "family": "mfi_reversion",
        "extra_params": {"mfi_period": (10, 20), "mfi_low": (15, 30), "mfi_high": (70, 85)},
        "indicators": [
            'df["mfi"] = ta.volume.money_flow_index(df["High"], df["Low"], df["Close"], df["Volume"], window=p["mfi_period"])',
        ],
        "long": 'uptrend & (df["mfi"] > p["mfi_low"]) & (df["mfi"].shift(1) <= p["mfi_low"])',
        "short": 'downtrend & (df["mfi"] < p["mfi_high"]) & (df["mfi"].shift(1) >= p["mfi_high"])',
    },
    # 68 — Aroon cross ─────────────────────────────────────────────────
    {
        "family": "aroon_cross",
        "extra_params": {"aroon_period": (15, 35)},
        "indicators": [
            'df["aroon_up"] = ta.trend.aroon_up(df["High"], df["Low"], window=p["aroon_period"])',
            'df["aroon_dn"] = ta.trend.aroon_down(df["High"], df["Low"], window=p["aroon_period"])',
        ],
        "long": 'uptrend & (df["aroon_up"] > df["aroon_dn"]) & (df["aroon_up"].shift(1) <= df["aroon_dn"].shift(1))',
        "short": 'downtrend & (df["aroon_up"] < df["aroon_dn"]) & (df["aroon_up"].shift(1) >= df["aroon_dn"].shift(1))',
    },
    # 69 — Vortex cross ────────────────────────────────────────────────
    {
        "family": "vortex_cross",
        "extra_params": {"vortex_period": (10, 25)},
        "indicators": [
            'df["vi_pos"] = ta.trend.vortex_indicator_pos(df["High"], df["Low"], df["Close"], window=p["vortex_period"])',
            'df["vi_neg"] = ta.trend.vortex_indicator_neg(df["High"], df["Low"], df["Close"], window=p["vortex_period"])',
        ],
        "long": 'uptrend & (df["vi_pos"] > df["vi_neg"]) & (df["vi_pos"].shift(1) <= df["vi_neg"].shift(1))',
        "short": 'downtrend & (df["vi_pos"] < df["vi_neg"]) & (df["vi_pos"].shift(1) >= df["vi_neg"].shift(1))',
    },
    # 70 — Awesome Oscillator zero cross (Bill Williams) ───────────────
    {
        "family": "awesome_osc_cross",
        "extra_params": {"ao_fast": (4, 7), "ao_slow": (28, 40)},
        "indicators": [
            'df["ao"] = ta.momentum.awesome_oscillator(df["High"], df["Low"], window1=p["ao_fast"], window2=p["ao_slow"])',
        ],
        "long": 'uptrend & (df["ao"] > 0) & (df["ao"].shift(1) <= 0)',
        "short": 'downtrend & (df["ao"] < 0) & (df["ao"].shift(1) >= 0)',
    },
    # 71 — Elder Force Index zero cross ────────────────────────────────
    {
        "family": "force_index_cross",
        "extra_params": {"fi_period": (9, 21)},
        "indicators": [
            'df["fi"] = ta.volume.force_index(df["Close"], df["Volume"], window=p["fi_period"])',
        ],
        "long": 'uptrend & (df["fi"] > 0) & (df["fi"].shift(1) <= 0)',
        "short": 'downtrend & (df["fi"] < 0) & (df["fi"].shift(1) >= 0)',
    },
    # 72 — TRIX zero cross ─────────────────────────────────────────────
    {
        "family": "trix_cross",
        "extra_params": {"trix_period": (10, 25)},
        "indicators": [
            'df["trix"] = ta.trend.trix(df["Close"], window=p["trix_period"])',
        ],
        "long": 'uptrend & (df["trix"] > 0) & (df["trix"].shift(1) <= 0)',
        "short": 'downtrend & (df["trix"] < 0) & (df["trix"].shift(1) >= 0)',
    },
    # 73 — DMI cross with ADX floor ────────────────────────────────────
    {
        "family": "dmi_cross",
        "extra_params": {"dmi_period": (10, 20), "adx_floor": (18, 28)},
        "indicators": [
            'df["di_pos"] = ta.trend.adx_pos(df["High"], df["Low"], df["Close"], window=p["dmi_period"])',
            'df["di_neg"] = ta.trend.adx_neg(df["High"], df["Low"], df["Close"], window=p["dmi_period"])',
            'df["adx_v"] = ta.trend.adx(df["High"], df["Low"], df["Close"], window=p["dmi_period"])',
        ],
        "long": 'uptrend & (df["adx_v"] > p["adx_floor"]) & (df["di_pos"] > df["di_neg"]) & (df["di_pos"].shift(1) <= df["di_neg"].shift(1))',
        "short": 'downtrend & (df["adx_v"] > p["adx_floor"]) & (df["di_pos"] < df["di_neg"]) & (df["di_pos"].shift(1) >= df["di_neg"].shift(1))',
    },
    # 74 — Ultimate Oscillator reversion ───────────────────────────────
    {
        "family": "ultimate_osc_reversion",
        "extra_params": {"uo_low": (25, 38), "uo_high": (62, 75)},
        "indicators": [
            'df["uo"] = ta.momentum.ultimate_oscillator(df["High"], df["Low"], df["Close"])',
        ],
        "long": 'uptrend & (df["uo"] > p["uo_low"]) & (df["uo"].shift(1) <= p["uo_low"])',
        "short": 'downtrend & (df["uo"] < p["uo_high"]) & (df["uo"].shift(1) >= p["uo_high"])',
    },
    # 75 — Order-flow proxy: delta pressure ────────────────────────────
    # True order flow needs tick data; this approximates the buy/sell
    # imbalance from where each bar closes inside its range, weighted by
    # volume, summed over a window.
    {
        "family": "orderflow_delta",
        "extra_params": {"of_period": (10, 30), "of_thresh": (0.10, 0.30)},
        "indicators": [
            'df["body_ratio"] = (df["Close"] - df["Open"]) / (df["High"] - df["Low"]).replace(0, np.nan)',
            'df["delta"] = df["body_ratio"] * df["Volume"]',
            'df["pressure"] = df["delta"].rolling(window=p["of_period"]).sum() / df["Volume"].rolling(window=p["of_period"]).sum().replace(0, np.nan)',
        ],
        "long": 'uptrend & (df["pressure"] > p["of_thresh"]) & (df["pressure"].shift(1) <= p["of_thresh"])',
        "short": 'downtrend & (df["pressure"] < -p["of_thresh"]) & (df["pressure"].shift(1) >= -p["of_thresh"])',
    },
    # 76 — Volume absorption then break ────────────────────────────────
    # Huge volume with a tiny range = passive orders absorbing aggression
    # at a level; the break of that bar's extreme signals who won.
    {
        "family": "volume_absorption",
        "extra_params": {"abs_period": (20, 50), "vol_mult": (1.5, 3.0), "range_frac": (0.3, 0.6)},
        "indicators": [
            'df["rng"] = df["High"] - df["Low"]',
            'df["rng_avg"] = df["rng"].rolling(window=p["abs_period"]).mean()',
            'df["vol_avg"] = df["Volume"].rolling(window=p["abs_period"]).mean()',
            'df["absorbed_prev"] = ((df["Volume"] > p["vol_mult"] * df["vol_avg"]) & (df["rng"] < p["range_frac"] * df["rng_avg"])).shift(1) == True',
        ],
        "long": 'uptrend & df["absorbed_prev"] & (df["Close"] > df["High"].shift(1))',
        "short": 'downtrend & df["absorbed_prev"] & (df["Close"] < df["Low"].shift(1))',
    },
]


# ---------------------------------------------------------------------------
# Agent
# ---------------------------------------------------------------------------
class TemplateFactory(BaseAgent):
    """Mass-generates strategies from parametric templates without an LLM."""

    name = "template_factory"

    def __init__(self, db):
        super().__init__(agent_id="template_factory", db=db)

    # ── lifecycle -----------------------------------------------------

    def setup(self):
        STRATEGIES_DIR.mkdir(parents=True, exist_ok=True)
        self.logger.info("TemplateFactory ready  (%d templates available)", len(TEMPLATES))

    def tick(self):
        # Exploitation bursts bypass the queue throttle: neighbors of a
        # proven winner are worth more than random new candidates.
        self._exploitation_burst()

        # Throttle when backtest queue is deep
        pending = self.db.fetchone(
            "SELECT COUNT(*) as cnt FROM strategies s "
            "LEFT JOIN backtest_results b ON s.id = b.strategy_id "
            "WHERE s.status = 'candidate' AND b.id IS NULL AND s.id LIKE 'T%'"
        )
        pending_cnt = pending["cnt"] if pending else 0
        if pending_cnt > 100:
            self.logger.debug(f"Queue deep ({pending_cnt} pending T-series) — skipping generation")
            return
        batch_size = self.get_config("batch_size", 5)
        generated = 0

        for _ in range(batch_size):
            template = self._pick_template()
            family = template["family"]
            all_ranges = {**BASE_PARAMS, **template["extra_params"]}
            params = self._random_params(all_ranges)

            strategy_id = self._next_id()
            code = self._build_code(strategy_id, template, params)

            is_valid, error = validate_strategy_code(code)
            if not is_valid:
                self.logger.warning(
                    "Template %s produced invalid code for %s: %s",
                    family, strategy_id, error,
                )
                self.emit_event("error", f"Invalid template code {strategy_id}: {error}")
                continue

            file_name = f"strategy_{strategy_id.lower()}.py"
            file_path = STRATEGIES_DIR / file_name
            file_path.write_text(code, encoding="utf-8")

            self._register(strategy_id, str(file_path), family)

            self.post_task(
                target_agent="backtest_runner",
                task_type="backtest",
                payload={"strategy_id": strategy_id, "file_path": str(file_path)},
                priority=5,
            )
            generated += 1
            self.logger.info("Generated %s (%s)", strategy_id, family)

        self.emit_event(
            "milestone",
            f"TemplateFactory batch complete: {generated}/{batch_size} strategies generated",
        )

    def tick_interval(self) -> float:
        return self.get_config("tick_interval", 30)

    # ── helpers -------------------------------------------------------

    def _exploitation_burst(self, per_winner: int = 20):
        """Local search around freshly deployed winners.

        When a strategy passes the full gauntlet (validation + walk-forward
        + holdout), its parameter point is PROVEN — the immediate
        neighborhood is the highest-probability place to find more
        deployables. Generate `per_winner` jittered clones (±12% per param)
        of each new winner. Robust edges live on plateaus: if the neighbors
        also validate, the edge is real; if none do, the winner was a spike.
        """
        last_id = self.get_config("burst_watermark") or 0
        rows = self.db.fetchall(
            "SELECT id, metadata FROM events "
            "WHERE id > ? AND event_type = 'milestone' "
            "AND event_message LIKE '%passed validation + walk-forward + holdout%' "
            "ORDER BY id",
            (last_id,),
        )
        if not rows:
            return

        templates_by_family = {t["family"]: t for t in TEMPLATES}
        for row in rows:
            last_id = row["id"]
            try:
                meta = json.loads(row["metadata"]) if row["metadata"] else {}
            except (json.JSONDecodeError, TypeError):
                continue
            sid = meta.get("strategy_id")
            if not sid:
                continue
            srow = self.db.fetchone(
                "SELECT family, file_path, parent_strategy FROM strategies WHERE id = ?",
                (sid,),
            )
            if not srow or not srow["family"]:
                continue

            # ANTI CHAIN-REACTION: burst children do NOT burst in turn.
            # Without this, one strong plateau family compounds 20 -> 400 ->
            # 8000 clones (observed live: hybrid_supertrend_rsi flooded the
            # whole pipeline in a day).
            if srow["parent_strategy"]:
                continue
            # A family only needs ~40 neighbors to prove/refute its plateau.
            kin = self.db.fetchone(
                "SELECT COUNT(*) AS cnt FROM strategies "
                "WHERE family = ? AND parent_strategy IS NOT NULL",
                (srow["family"],),
            )
            if kin and (kin["cnt"] or 0) >= 40:
                continue

            template = templates_by_family.get(srow["family"])
            if template is None:
                continue  # evolved/ensemble winners are handled by evolution_agent

            params = self._load_params_from_file(srow["file_path"])
            if not params:
                continue

            made = 0
            for _ in range(per_winner):
                jittered = {}
                for k, v in params.items():
                    if isinstance(v, bool) or not isinstance(v, (int, float)):
                        jittered[k] = v
                    else:
                        nv = v * (1.0 + random.uniform(-0.12, 0.12))
                        jittered[k] = int(round(nv)) if isinstance(v, int) else round(nv, 4)

                new_id = self._next_id()
                code = self._build_code(new_id, template, jittered)
                is_valid, _err = validate_strategy_code(code)
                if not is_valid:
                    continue
                fp = STRATEGIES_DIR / f"strategy_{new_id.lower()}.py"
                fp.write_text(code, encoding="utf-8")
                self._register(
                    new_id, str(fp), srow["family"], parent=sid,
                    description=f"Burst neighbor of winner {sid}",
                )
                made += 1

            self.emit_event(
                "milestone",
                f"Exploitation burst: {made} neighbors of winner {sid} ({srow['family']})",
                metadata={"winner": sid, "family": srow["family"], "generated": made},
            )
            self.logger.info(f"Exploitation burst: {made} neighbors of {sid}")

        self.set_config("burst_watermark", last_id)

    @staticmethod
    def _load_params_from_file(file_path: str) -> dict:
        """Extract the PARAMS dict from a generated strategy file."""
        try:
            text = Path(file_path).read_text(encoding="utf-8")
            m = re.search(r"^PARAMS = (.+)$", text, re.MULTILINE)
            if m:
                return ast.literal_eval(m.group(1))
        except Exception:
            pass
        return {}

    def _pick_template(self):
        """Pick template weighted by each family's honest quality density.

        A family earns weight from the fraction of its tested variants that
        show real quality (PF >= 1.3, DD <= 25%, 30+ trades) plus a strong
        bonus per validated strategy. 30% of picks stay pure exploration so
        no family starves; smoothing keeps untested families in the game.
        """
        if random.random() < 0.30:
            return random.choice(TEMPLATES)  # exploration

        rows = self.db.fetchall(
            "SELECT s.family, COUNT(*) AS n_tested, "
            "SUM(CASE WHEN v.pf >= 1.3 AND v.dd <= 0.25 AND v.trades >= 30 "
            "    THEN 1 ELSE 0 END) AS n_quality, "
            "SUM(CASE WHEN s.status = 'validated' THEN 1 ELSE 0 END) AS n_validated "
            "FROM (SELECT strategy_id, MAX(profit_factor) AS pf, "
            "             MAX(total_trades) AS trades, MIN(max_drawdown) AS dd "
            "      FROM backtest_results GROUP BY strategy_id) v "
            "JOIN strategies s ON s.id = v.strategy_id "
            "WHERE s.family IS NOT NULL "
            "GROUP BY s.family"
        )
        stats = {r["family"]: r for r in rows}

        weights = []
        for t in TEMPLATES:
            r = stats.get(t["family"])
            if r:
                n_tested = r["n_tested"] or 0
                n_quality = r["n_quality"] or 0
                n_validated = r["n_validated"] or 0
                # Smoothed quality rate. The validated bonus is CAPPED: weight
                # must reflect marginal information value, not accumulated
                # glory — an uncapped bonus made the factory generate one
                # solved family almost exclusively (observed runaway).
                w = (1.0 + 2.0 * min(n_quality, 10) + 10.0 * min(n_validated, 3)) / (n_tested + 5.0)
                # A solved family (10+ validated) teaches us nothing new.
                if n_validated >= 10:
                    w *= 0.05
            else:
                w = 1.0 / 5.0  # untested family: neutral prior
            weights.append(max(w, 0.01))

        return random.choices(TEMPLATES, weights=weights, k=1)[0]

    # Combination logic gene: how the trigger conditions are AND/OR/majority
    # combined. Weighted toward "and" (the proven strict default) but the
    # search now explores looser, higher-frequency variants too.
    LOGIC_MODES = ["and", "and", "or", "majority"]

    @staticmethod
    def _split_conditions(cond: str):
        """Split a template condition string into (trend_term, [triggers]).

        Conditions are top-level '&'-joined clauses; the first is the
        mandatory EMA trend filter (uptrend/downtrend). The rest are the
        triggers that the 'logic' gene recombines. Splitting only at top
        level (paren depth 0) keeps nested expressions intact.
        """
        parts, depth, cur = [], 0, ""
        i = 0
        while i < len(cond):
            ch = cond[i]
            if ch == "(":
                depth += 1
            elif ch == ")":
                depth -= 1
            if ch == "&" and depth == 0:
                parts.append(cur.strip())
                cur = ""
            else:
                cur += ch
            i += 1
        if cur.strip():
            parts.append(cur.strip())
        parts = [p for p in parts if p]
        if not parts:
            return "True", []
        return parts[0], parts[1:]

    @staticmethod
    def _random_params(ranges: dict) -> dict:
        """Sample concrete parameter values from ranges, plus the logic gene."""
        params = {}
        for key, (lo, hi) in ranges.items():
            if isinstance(lo, int) and isinstance(hi, int):
                params[key] = random.randint(lo, hi)
            else:
                params[key] = round(random.uniform(lo, hi), 4)
        params["logic"] = random.choice(TemplateFactory.LOGIC_MODES)
        return params

    def _build_code(self, strategy_id: str, template: dict, params: dict) -> str:
        """Fill the STRATEGY_TEMPLATE placeholders and return source code."""
        indicator_lines = "\n".join(f"    {line}" for line in template["indicators"])
        long_trend, long_trig = self._split_conditions(template["long"])
        short_trend, short_trig = self._split_conditions(template["short"])
        code = STRATEGY_TEMPLATE
        code = code.replace("__ID__", strategy_id)
        code = code.replace("__FAMILY__", template["family"])
        code = code.replace("__PARAMS__", repr(params))
        code = code.replace("__INDICATORS__", indicator_lines)
        code = code.replace("__LONG_TREND__", long_trend)
        code = code.replace("__SHORT_TREND__", short_trend)
        code = code.replace("__LONG_TRIG__", ", ".join(long_trig))
        code = code.replace("__SHORT_TRIG__", ", ".join(short_trig))
        return code

    def _next_id(self) -> str:
        """Return the next T-series strategy ID (T00001, T00002, ...)."""
        row = self.db.fetchone(
            "SELECT id FROM strategies WHERE id LIKE 'T%' ORDER BY id DESC LIMIT 1"
        )
        if row:
            last_num = int(row["id"][1:])
            return f"T{last_num + 1:05d}"
        return "T00001"

    def _register(self, strategy_id: str, file_path: str, family: str,
                  parent: str = None, description: str = None) -> None:
        """Insert strategy record into the strategies table."""
        self.db.execute(
            "INSERT OR IGNORE INTO strategies "
            "(id, file_path, family, description, created_by, status, parent_strategy) "
            "VALUES (?, ?, ?, ?, ?, ?, ?)",
            (
                strategy_id,
                file_path,
                family,
                description or f"Auto-generated {family} strategy",
                self.agent_id,
                "candidate",
                parent,
            ),
        )
